export interface Calculator {
  slug: string;
  name: string;
  description: string;
  category: string;
  emoji: string;
  keywords: string[];
  featured?: boolean;
}

const rawCalculators: Calculator[] = [
  // FINANCIAL CALCULATORS (80+)
  { slug: '401k-calculator', name: '401K Calculator', description: 'Free 401K calculator to plan and estimate a 401K balance and payout amount in retirement or help with early withdrawals or maximizing employer match.', category: 'financial', emoji: '🏛️', keywords: ['401k', 'retirement', 'contribution', 'employer match'], featured: true },
  { slug: 'apr-calculator', name: 'APR Calculator', description: 'Free calculator to find out the real APR of a loan, considering all the fees and extra charges.', category: 'financial', emoji: '🔢', keywords: ['apr', 'annual percentage rate', 'loan cost'] },
  { slug: 'amortization-calculator', name: 'Amortization Calculator', description: 'This amortization calculator returns monthly payment amounts as well as displays a schedule, graph, and pie chart breakdown of an amortized loan.', category: 'financial', emoji: '📊', keywords: ['amortization', 'loan schedule', 'payment schedule'], featured: true },
  { slug: 'annuity-calculator', name: 'Annuity Calculator', description: 'Free annuity calculator to forecast the growth of an annuity with optional annual or monthly additions.', category: 'financial', emoji: '📋', keywords: ['annuity', 'annuity payment', 'retirement'] },
  { slug: 'annuity-payout-calculator', name: 'Annuity Payout Calculator', description: 'Free annuity payout calculator to find the payout amount based on fixed-length or to find the length the fund can last based on a given payment amount.', category: 'financial', emoji: '💸', keywords: ['annuity payout', 'income stream', 'retirement'] },
  { slug: 'auto-lease-calculator', name: 'Auto Lease Calculator', description: 'Free auto lease calculator to find the monthly payment and total cost for an auto lease.', category: 'financial', emoji: '🚙', keywords: ['auto lease', 'car lease', 'lease payment'] },
  { slug: 'auto-loan-calculator', name: 'Auto Loan Calculator', description: 'Free auto loan calculator to determine the monthly payment and total cost of an auto loan, while accounting for sales tax, fees, trade-in value, and more.', category: 'financial', emoji: '🚗', keywords: ['auto loan', 'car loan', 'vehicle payment'], featured: true },
  { slug: 'average-return-calculator', name: 'Average Return Calculator', description: 'Free calculator to find the average return of an investment considering all deposits and withdrawals or the average return of different holding lengths.', category: 'financial', emoji: '📈', keywords: ['average return', 'annual return', 'cagr'] },
  { slug: 'business-loan-calculator', name: 'Business Loan Calculator', description: 'Free business loan calculator that deals with complex repayment options and returns real APR/cost of a business or SBA loan.', category: 'financial', emoji: '🏢', keywords: ['business loan', 'commercial loan', 'sba loan'] },
  { slug: 'bond-calculator', name: 'Bond Calculator', description: 'Free calculator to compute various parameters of a bond including price and accrued interest.', category: 'financial', emoji: '📜', keywords: ['bond', 'yield', 'coupon', 'maturity'] },
  { slug: 'budget-calculator', name: 'Budget Calculator', description: 'Detailed free budget calculator to plan personal finances with Debt-to-Income (DTI) ratio and expense breakdown.', category: 'financial', emoji: '📒', keywords: ['budget', 'personal budget', 'spending', 'income'] },
  { slug: 'cash-back-or-low-interest-calculator', name: 'Cash Back or Low Interest Calculator', description: 'Free calculator to evaluate the options of either cash back or low interest offers when buying a car.', category: 'financial', emoji: '💰', keywords: ['cash back', 'low interest', 'credit card'] },
  { slug: 'cd-calculator', name: 'CD Calculator', description: 'Free calculator to find the total interest, end balance, and the growth chart of a Certificate of Deposit.', category: 'financial', emoji: '💿', keywords: ['cd', 'certificate of deposit', 'savings', 'apy'] },
  { slug: 'college-cost-calculator', name: 'College Cost Calculator', description: 'Free calculator to estimate how much college will cost in the U.S. using average college cost data or self-defined data.', category: 'financial', emoji: '📚', keywords: ['college cost', 'tuition', 'education cost'] },
  { slug: 'commission-calculator', name: 'Commission Calculator', description: 'Free calculator to compute simple percentage commission, tiered commission, or commission that includes a base amount.', category: 'financial', emoji: '💼', keywords: ['commission', 'sales commission', 'agent fee'] },
  { slug: 'compound-interest-calculator', name: 'Compound Interest Calculator', description: 'Free compound interest calculator to convert and compare interest rates of different compounding periods.', category: 'financial', emoji: '📐', keywords: ['compound interest', 'savings growth', 'interest'], featured: true },
  { slug: 'credit-card-calculator', name: 'Credit Card Calculator', description: 'Free credit card calculator to find the time it will take to pay off a balance or the amount necessary to pay it off within a certain time frame.', category: 'financial', emoji: '💳', keywords: ['credit card', 'interest', 'minimum payment', 'payoff'] },
  { slug: 'credit-card-payoff-calculator', name: 'Credit Cards Payoff Calculator', description: 'Free credit card payoff calculator for finding the best way to pay off multiple credit cards.', category: 'financial', emoji: '✂️', keywords: ['credit card payoff', 'debt', 'multiple cards'] },
  { slug: 'currency-calculator', name: 'Currency Calculator', description: 'Free currency calculator to convert between most of the global currencies using live or custom exchange rates.', category: 'financial', emoji: '💱', keywords: ['currency', 'exchange', 'forex', 'convert'] },
  { slug: 'debt-consolidation-calculator', name: 'Debt Consolidation Calculator', description: 'Free debt consolidation calculator to evaluate the consolidation of debts such as credit cards debts, auto loans, or personal loans based on the real cost.', category: 'financial', emoji: '🔗', keywords: ['debt consolidation', 'combine debt', 'lower rate'] },
  { slug: 'debt-payoff-calculator', name: 'Debt Payoff Calculator', description: 'Free calculator for finding the best way to pay off multiple debts such as those related to credit cards, auto loans, or mortgages.', category: 'financial', emoji: '⛓️', keywords: ['debt payoff', 'debt free', 'payoff strategy'] },
  { slug: 'debt-ratio-calculator', name: 'Debt-to-Income Ratio Calculator', description: 'Free calculator to find both the front end and back end Debt-to-Income (DTI) ratio for personal finance use.', category: 'financial', emoji: '⚖️', keywords: ['debt to income', 'dti ratio', 'mortgage qualify'] },
  { slug: 'depreciation-calculator', name: 'Depreciation Calculator', description: 'Free depreciation calculator using the straight line, declining balance, or sum of the year\'s digits methods.', category: 'financial', emoji: '📉', keywords: ['depreciation', 'asset', 'straight line', 'macrs'] },
  { slug: 'discount-calculator', name: 'Discount Calculator', description: 'Online calculator to determine the final price after discount, the amount saved, or the original price before discount.', category: 'financial', emoji: '🏷️', keywords: ['discount', 'sale price', 'percent off'] },
  { slug: 'down-payment-calculator', name: 'Down Payment Calculator', description: 'Free down payment calculator to find the amount of upfront cash needed, down payment percentage, or an affordable home price.', category: 'financial', emoji: '💵', keywords: ['down payment', 'home purchase', 'closing costs'] },
  { slug: 'estate-tax-calculator', name: 'Estate Tax Calculator', description: 'Free estate tax calculator to estimate federal estate tax in the U.S. and check the latest estate tax rate.', category: 'financial', emoji: '🏛️', keywords: ['estate tax', 'inheritance', 'estate planning'] },
  { slug: 'fha-loan-calculator', name: 'FHA Loan Calculator', description: 'Free FHA loan calculator to find the monthly payment, total interest, and amortization details of an FHA loan.', category: 'financial', emoji: '🏠', keywords: ['fha loan', 'fha mortgage', 'government loan'] },
  { slug: 'finance-calculator', name: 'Finance Calculator', description: 'Free online finance calculator to find the future value (FV), compounding periods (N), interest rate (I/Y), periodic payment (PMT), and present value (PV).', category: 'financial', emoji: '🏦', keywords: ['finance', 'financial', 'calculator'] },
  { slug: 'future-value-calculator', name: 'Future Value Calculator', description: 'Free calculator to find the future value and display a growth chart of a present amount or periodic deposits.', category: 'financial', emoji: '🔮', keywords: ['future value', 'fv', 'compound growth'] },
  { slug: 'heloc-calculator', name: 'HELOC Calculator', description: 'Free calculator that finds the HELOC amount you can borrow, along with the monthly payment, interest, total cost, and APR.', category: 'financial', emoji: '🏡', keywords: ['heloc', 'home equity line', 'credit line'] },
  { slug: 'home-equity-loan-calculator', name: 'Home Equity Loan Calculator', description: 'Free calculator that finds the home equity loan amount you can borrow, along with the monthly payment, interest, total cost, and APR.', category: 'financial', emoji: '🏠', keywords: ['home equity', 'equity loan', 'second mortgage'] },
  { slug: 'house-affordability-calculator', name: 'House Affordability Calculator', description: 'Free house affordability calculator to estimate an affordable house price based on factors such as income, debt, down payment, or simply budget.', category: 'financial', emoji: '🏘️', keywords: ['house affordability', 'home buying', 'mortgage qualify'] },
  { slug: 'inflation-calculator', name: 'Inflation Calculator', description: 'Free inflation calculator that runs on U.S. CPI data or a custom inflation rate. Also, find the historical U.S. inflation data and learn more about inflation.', category: 'financial', emoji: '💹', keywords: ['inflation', 'purchasing power', 'cpi'] },
  { slug: 'interest-calculator', name: 'Interest Calculator', description: 'Free compound interest calculator to find the interest, final balance, and schedule using either a fixed initial investment and/or periodic contributions.', category: 'financial', emoji: '📈', keywords: ['interest', 'savings', 'investment'], featured: true },
  { slug: 'interest-rate-calculator', name: 'Interest Rate Calculator', description: 'Free online calculator to find the interest rate as well as the total interest cost of an amortized loan with a fixed monthly payback amount.', category: 'financial', emoji: '🔢', keywords: ['interest rate', 'apr', 'apy'] },
  { slug: 'investment-calculator', name: 'Investment Calculator', description: 'Free investment calculator to evaluate various investment situations considering starting and ending balance, contributions, return rate, and investment length.', category: 'financial', emoji: '📉', keywords: ['investment', 'returns', 'growth', 'stocks'], featured: true },
  { slug: 'ira-calculator', name: 'IRA Calculator', description: 'Free IRA calculator to estimate growth, tax savings, total return, and balance at retirement of Traditional, Roth IRA, SIMPLE, and SEP IRAs.', category: 'financial', emoji: '💰', keywords: ['ira', 'traditional ira', 'retirement savings'] },
  { slug: 'irr-calculator', name: 'IRR Calculator', description: 'This calculator can calculate the Internal Rate of Return (IRR) for scenarios involving a fixed recurring cash flow, no cash flow, or irregular annual cash flows.', category: 'financial', emoji: '📊', keywords: ['irr', 'internal rate of return', 'investment'] },
  { slug: 'lease-calculator', name: 'Lease Calculator', description: 'Free lease calculator to find the monthly payment or effective interest rate as well as interest cost of a lease.', category: 'financial', emoji: '📝', keywords: ['lease', 'lease payment', 'rent to own'] },
  { slug: 'loan-calculator', name: 'Loan Calculator', description: 'Free loan calculator to find the repayment plan, interest cost, and amortization schedule of conventional amortized loans, deferred payment loans, and bonds.', category: 'financial', emoji: '💳', keywords: ['loan', 'payment', 'interest', 'borrow'], featured: true },
  { slug: 'margin-calculator', name: 'Margin Calculator', description: 'Three free calculators for profit margin, stock trading margin, or currency exchange margin calculations.', category: 'financial', emoji: '💹', keywords: ['margin', 'profit margin', 'markup', 'gross margin'] },
  { slug: 'marriage-tax-calculator', name: 'Marriage Tax Calculator', description: 'Free calculator to estimate the financial consequences of marriage to the participant individuals in terms of U.S. federal income taxation.', category: 'financial', emoji: '💍', keywords: ['marriage tax', 'married filing', 'tax penalty'] },
  { slug: 'mortgage-calculator', name: 'Mortgage Calculator', description: 'Free mortgage calculator to find monthly payment, total home ownership cost, and amortization schedule with options for taxes, PMI, HOA, and early payoff.', category: 'financial', emoji: '🏠', keywords: ['mortgage', 'home loan', 'house payment', 'monthly payment'], featured: true },
  { slug: 'mortgage-amortization-calculator', name: 'Mortgage Amortization Calculator', description: 'Free online mortgage amortization calculator including amortization schedules and the related curves.', category: 'financial', emoji: '📋', keywords: ['mortgage amortization', 'amortization schedule', 'payoff schedule'] },
  { slug: 'mortgage-calculator-uk', name: 'Mortgage Calculator UK', description: 'Free online mortgage calculator specifically customized for use in the UK including amortization tables and the respective graphs.', category: 'financial', emoji: '🇬🇧', keywords: ['uk mortgage', 'british mortgage', 'stamp duty'] },
  { slug: 'mortgage-payoff-calculator', name: 'Mortgage Payoff Calculator', description: 'Free mortgage payoff calculator to evaluate options to pay off a mortgage earlier, such as extra payments, bi-weekly payments, or paying back altogether.', category: 'financial', emoji: '🏡', keywords: ['mortgage payoff', 'early payoff', 'extra payment'] },
  { slug: 'mutual-fund-calculator', name: 'Mutual Fund Calculator', description: 'Free calculator to estimate the ending balance and net return of mutual funds including charges and fees.', category: 'financial', emoji: '📊', keywords: ['mutual fund', 'fund returns', 'investment'] },
  { slug: 'payback-period-calculator', name: 'Payback Period Calculator', description: 'Free calculator to find payback period, discounted payback period, and the average return of either steady or irregular cash flows.', category: 'financial', emoji: '⏱️', keywords: ['payback period', 'investment', 'break even'] },
  { slug: 'payment-calculator', name: 'Payment Calculator', description: 'Free payment calculator to find monthly payment amount or time period to pay off a loan using a fixed term or a fixed payment.', category: 'financial', emoji: '💰', keywords: ['payment', 'monthly', 'loan payment'], featured: true },
  { slug: 'pension-calculator', name: 'Pension Calculator', description: 'Free calculator to help optimize pension payout or planning considering lump sum or monthly payouts, single-life or joint and survivor payouts.', category: 'financial', emoji: '👴', keywords: ['pension', 'retirement income', 'defined benefit'] },
  { slug: 'personal-loan-calculator', name: 'Personal Loan Calculator', description: 'Free personal loan calculator that returns the monthly payment, real loan cost, and the APR after considering the fee, insurance, interest of a personal loan.', category: 'financial', emoji: '🤝', keywords: ['personal loan', 'unsecured loan', 'loan payment'] },
  { slug: 'present-value-calculator', name: 'Present Value Calculator', description: 'Free financial calculator to find the present value of a future amount or a stream of annuity payments.', category: 'financial', emoji: '📅', keywords: ['present value', 'pv', 'discounted cash flow'] },
  { slug: 'refinance-calculator', name: 'Refinance Calculator', description: 'Free calculator to plan the refinancing of loans by comparing existing and refinanced loans side by side.', category: 'financial', emoji: '🔄', keywords: ['refinance', 'refi', 'lower rate', 'break even'] },
  { slug: 'rent-calculator', name: 'Rent Calculator', description: 'Free rent calculator to estimate the range of affordable monthly rent based on income and debt.', category: 'financial', emoji: '🏢', keywords: ['rent', 'rental', 'apartment'] },
  { slug: 'rent-vs-buy-calculator', name: 'Rent vs. Buy Calculator', description: 'Free calculator to compare the financial aspects of renting vs. buying a house accounting for interest, tax, fees, and many other factors.', category: 'financial', emoji: '⚖️', keywords: ['rent vs buy', 'home buying', 'financial comparison'] },
  { slug: 'rental-property-calculator', name: 'Rental Property Calculator', description: 'Free rental property calculator estimates IRR, capitalization rate, cash flow, and other financial indicators of a rental or investment property.', category: 'financial', emoji: '🏠', keywords: ['rental property', 'cash flow', 'cap rate', 'roi'] },
  { slug: 'repayment-calculator', name: 'Repayment Calculator', description: 'Free repayment calculator to find different ways to repay a loan, based on compounding periods, payment frequency, and fixed loan term or fixed payback amount.', category: 'financial', emoji: '↩️', keywords: ['repayment', 'loan repayment', 'pay back'] },
  { slug: 'retirement-calculator', name: 'Retirement Calculator', description: 'Free calculators that help with retirement planning with inflation, social security, life expectancy, and many more factors being taken into account.', category: 'financial', emoji: '🏖️', keywords: ['retirement', 'savings', '401k', 'pension'], featured: true },
  { slug: 'rmd-calculator', name: 'RMD Calculator', description: 'This calculator computes the Required Minimum Distribution (RMD) of your retirement accounts and predicts future distributions.', category: 'financial', emoji: '🔄', keywords: ['rmd', 'required minimum distribution', 'retirement withdrawal'] },
  { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Free return on investment (ROI) calculator that returns total ROI rate and annualized ROI using either actual dates of investment or simply investment length.', category: 'financial', emoji: '💰', keywords: ['roi', 'return on investment', 'profit'] },
  { slug: 'roth-ira-calculator', name: 'Roth IRA Calculator', description: 'Free Roth IRA calculator to estimate growth, tax savings, total return, and balance at retirement with the option to contribute regularly.', category: 'financial', emoji: '🌱', keywords: ['roth ira', 'tax free', 'retirement savings'] },
  { slug: 'salary-calculator', name: 'Salary Calculator', description: 'A free calculator to convert a salary between its hourly, biweekly, monthly, and annual amounts accounting for holidays and vacation days.', category: 'financial', emoji: '💼', keywords: ['salary', 'hourly', 'annual', 'pay'], featured: true },
  { slug: 'sales-tax-calculator', name: 'Sales Tax Calculator', description: 'Free calculator to find the sales tax amount/rate, before tax price, and after-tax price. Also check sales tax rates in different states of the U.S.', category: 'financial', emoji: '🛒', keywords: ['sales tax', 'tax rate', 'total price'] },
  { slug: 'savings-calculator', name: 'Savings Calculator', description: 'Free calculator to find out the balance and interest of a savings account while accounting for tax, periodic contributions, compounding frequency.', category: 'financial', emoji: '🐷', keywords: ['savings', 'save money', 'savings account'] },
  { slug: 'simple-interest-calculator', name: 'Simple Interest Calculator', description: 'This calculator computes the simple interest and end balance of a savings or investment account. It also calculates other parameters of the simple interest formula.', category: 'financial', emoji: '➕', keywords: ['simple interest', 'principal', 'rate', 'time'] },
  { slug: 'social-security-calculator', name: 'Social Security Calculator', description: 'Free Social Security calculator to find the best age to start SS benefits, or compare differences between starting SS at different ages in the U.S.', category: 'financial', emoji: '🤝', keywords: ['social security', 'ssa', 'benefits', 'retirement'] },
  { slug: 'student-loan-calculator', name: 'Student Loan Calculator', description: 'Free calculator to evaluate student loans by estimating the interest cost, helping to understand the balance, and evaluating pay-off options.', category: 'financial', emoji: '🎓', keywords: ['student loan', 'college debt', 'education loan'] },
  { slug: 'take-home-pay-calculator', name: 'Take-Home-Paycheck Calculator', description: 'Free calculator to find the actual paycheck amount taken home after taxes and deductions from salary.', category: 'financial', emoji: '💵', keywords: ['take home pay', 'net pay', 'paycheck', 'deductions'] },
  { slug: 'tax-calculator', name: 'Income Tax Calculator', description: 'Free online income tax calculator to estimate U.S federal tax refund or owed amount for both salary earners and independent contractors.', category: 'financial', emoji: '🧾', keywords: ['income tax', 'federal tax', 'state tax', 'tax return'], featured: true },
  { slug: 'va-mortgage-calculator', name: 'VA Mortgage Calculator', description: 'Free VA mortgage calculator to find the monthly payment, total interest, funding fee, and amortization details of a VA loan.', category: 'financial', emoji: '🎖️', keywords: ['va loan', 'veteran mortgage', 'va mortgage'] },
  { slug: 'vat-calculator', name: 'VAT Calculator', description: 'Free VAT (value-added tax) calculator to find any value of the net before VAT tax amount, tax price, VAT tax rate, and final VAT inclusive price.', category: 'financial', emoji: '🧮', keywords: ['vat', 'value added tax', 'uk tax', 'europe tax'] },
  { slug: 'boat-loan-calculator', name: 'Boat Loan Calculator', description: 'Free boat loan calculator to determine the monthly payment and total cost of a boat loan, while accounting for sales tax, fees, trade-in value, and more.', category: 'financial', emoji: '⛵', keywords: ['boat loan', 'marine loan', 'watercraft'] },
  { slug: 'canadian-mortgage-calculator', name: 'Canadian Mortgage Calculator', description: 'Free online mortgage calculator specifically customized for use in Canada including amortization tables and the respective graphs.', category: 'financial', emoji: '🍁', keywords: ['canadian mortgage', 'canada mortgage', 'cmhc'] },
  { slug: 'percent-off-calculator', name: 'Percent Off Calculator', description: 'Online calculator to compute the final price after a percentage discount.', category: 'financial', emoji: '🏷️', keywords: ['percent off', 'discount', 'sale price'] },

  // HEALTH & FITNESS CALCULATORS (30+)
  { slug: 'bmi-calculator', name: 'BMI Calculator', description: 'Free Body Mass Index calculator gives out the BMI value and categorizes BMI based on provided information from WHO and CDC.', category: 'health', emoji: '⚖️', keywords: ['bmi', 'body mass index', 'weight', 'height'], featured: true },
  { slug: 'calorie-calculator', name: 'Calorie Calculator', description: 'This calorie calculator estimates the number of calories needed each day to maintain, lose, or gain weight.', category: 'health', emoji: '🥗', keywords: ['calorie', 'calories', 'diet', 'nutrition'], featured: true },
  { slug: 'body-fat-calculator', name: 'Body Fat Calculator', description: 'This free body fat calculator estimates body fat percentage based on the U.S. Navy Method and the BMI method.', category: 'health', emoji: '💪', keywords: ['body fat', 'body composition', 'fat percentage'] },
  { slug: 'bmr-calculator', name: 'BMR Calculator', description: 'This free BMR calculator estimates basal metabolic rate based on well-known formulas and learns more about variables that affect BMR.', category: 'health', emoji: '🔥', keywords: ['bmr', 'basal metabolic rate', 'metabolism', 'calories'] },
  { slug: 'macro-calculator', name: 'Macro Calculator', description: 'This macro calculator estimates the macronutrient needs of a person based on their age, physical characteristics, activity level, and bodyweight goals.', category: 'health', emoji: '🥩', keywords: ['macro', 'macronutrients', 'protein', 'carbs', 'fat'] },
  { slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', description: 'This free ideal weight calculator estimates ideal healthy bodyweight based on age, gender, and height based on several popular formulas.', category: 'health', emoji: '🎯', keywords: ['ideal weight', 'healthy weight', 'target weight'] },
  { slug: 'pregnancy-calculator', name: 'Pregnancy Calculator', description: 'This calculator provides an estimated pregnancy schedule based on the due date, last period date, ultrasound date, conception date, or IVF transfer date.', category: 'health', emoji: '🤰', keywords: ['pregnancy', 'due date', 'weeks pregnant', 'trimester'] },
  { slug: 'pregnancy-weight-gain-calculator', name: 'Pregnancy Weight Gain Calculator', description: 'This pregnancy weight gain calculator provides a recommended weight gain schedule on a week-by-week basis based on pre-pregnancy bodyweight and IOM guidelines.', category: 'health', emoji: '🍼', keywords: ['pregnancy weight', 'gestational weight', 'prenatal'] },
  { slug: 'due-date-calculator', name: 'Due Date Calculator', description: 'This free due date calculator estimates the due date based on the menstrual cycle, ultrasound, conception date, or IVF transfer date.', category: 'health', emoji: '📅', keywords: ['due date', 'pregnancy', 'gestational age', 'edd'] },
  { slug: 'pace-calculator', name: 'Pace Calculator', description: 'This free pace calculator computes pace, time, and distance, given values for two of the variables. It can also be used for training purposes.', category: 'health', emoji: '🏃', keywords: ['pace', 'running', 'marathon', 'race time'] },
  { slug: 'army-body-fat-calculator', name: 'Army Body Fat Calculator', description: 'This calculator computes body fat percentage using methods from the Army Body Fat Assessment of the Army Body Composition Program.', category: 'health', emoji: '🎖️', keywords: ['army body fat', 'military', 'body fat tape test'] },
  { slug: 'calories-burned-calculator', name: 'Calories Burned Calculator', description: 'Free calculator to estimate the number of calories burned during routine daily activities or a workout based on activity duration.', category: 'health', emoji: '🏃', keywords: ['calories burned', 'exercise', 'activity'] },
  { slug: 'one-rep-max-calculator', name: 'One Rep Max Calculator', description: 'This free calculator estimates a person\'s one rep max (1RM) based on the number of repetitions they can perform with a given weight.', category: 'health', emoji: '💪', keywords: ['one rep max', 'lifting', 'strength'] },
  { slug: 'carbohydrate-calculator', name: 'Carbohydrate Calculator', description: 'This free carbohydrate calculator estimates a range of daily carbohydrate requirements based on factors such as daily activity, height, and weight.', category: 'health', emoji: '🍞', keywords: ['carbohydrate', 'carbs', 'nutrition'] },
  { slug: 'lean-body-mass-calculator', name: 'Lean Body Mass Calculator', description: 'This free lean body mass (LBM) calculator estimates LBM based on body weight, height, age, and gender.', category: 'health', emoji: '💪', keywords: ['lean body mass', 'lbm', 'muscle'] },
  { slug: 'healthy-weight-calculator', name: 'Healthy Weight Calculator', description: 'This calculator estimates a healthy body weight range based on body mass index and learns more about the effects of being underweight, overweight, or obese.', category: 'health', emoji: '✅', keywords: ['healthy weight', 'normal weight', 'bmi range'] },
  { slug: 'ovulation-calculator', name: 'Ovulation Calculator', description: 'This free ovulation calculator provides estimates of a person\'s possible ovulation windows and corresponding due dates over six menstrual cycles.', category: 'health', emoji: '🌸', keywords: ['ovulation', 'fertile window', 'conception'] },
  { slug: 'protein-calculator', name: 'Protein Calculator', description: 'This free protein calculator estimates the amount of protein a person needs each day to remain healthy based on certain averages and recommendations.', category: 'health', emoji: '🥚', keywords: ['protein', 'nutrition', 'diet'] },
  { slug: 'fat-intake-calculator', name: 'Fat Intake Calculator', description: 'This free fat intake calculator estimates the amount of dietary fat a person should consume daily based on age, height, weight, and activity.', category: 'health', emoji: '🥑', keywords: ['fat intake', 'nutrition', 'dietary fat'] },
  { slug: 'tdee-calculator', name: 'TDEE Calculator', description: 'This calculator estimates the Total Daily Energy Expenditure (TDEE) of a person based on their age, physical characteristics, and activity level.', category: 'health', emoji: '🔥', keywords: ['tdee', 'calories burned', 'energy expenditure'] },
  { slug: 'body-surface-area-calculator', name: 'Body Surface Area Calculator', description: 'This body surface area calculator estimates the surface area of a person\'s body based on body weight and height. It compares the results of several formulas.', category: 'health', emoji: '📏', keywords: ['body surface', 'bsa', 'surface area'] },
  { slug: 'body-type-calculator', name: 'Body Type Calculator', description: 'This free body type calculator estimates body type based on provided measurements of bust, waist, and hip size.', category: 'health', emoji: '👗', keywords: ['body shape', 'body type', 'measurements'] },
  { slug: 'bra-size-calculator', name: 'Bra Size Calculator', description: 'This calculator estimates bra size based on bust size, frame size, and common measurement standards. Also converts bra sizes in the US, UK, EU, and Australia.', category: 'health', emoji: '👙', keywords: ['bra size', 'clothing size', 'measurement'] },
  { slug: 'bac-calculator', name: 'BAC Calculator', description: 'Online calculator to estimate the Blood Alcohol Concentration (BAC) level based on the amount of alcohol consumed, time elapsed, gender, and body weight.', category: 'health', emoji: '⚠️', keywords: ['bac', 'blood alcohol', 'alcohol level'] },
  { slug: 'gfr-calculator', name: 'GFR Calculator', description: 'This GFR calculator estimates the glomerular filtration rate for both adults and children based on serum creatinine value.', category: 'health', emoji: '🫘', keywords: ['gfr', 'kidney function', 'creatinine'] },
  { slug: 'height-calculator', name: 'Height Calculator', description: 'This free height calculator predicts a child\'s adult height based on linear regression analysis. It can also convert between different units of height.', category: 'health', emoji: '📏', keywords: ['height', 'prediction', 'measurement'] },
  { slug: 'target-heart-rate-calculator', name: 'Target Heart Rate Calculator', description: 'This free calculator calculates the target heart rate range for maximizing exercise benefit based on age and resting heart rate.', category: 'health', emoji: '❤️', keywords: ['heart rate', 'exercise', 'target'] },

  // MATH & SCIENCE CALCULATORS (50+)
  { slug: 'scientific-calculator', name: 'Scientific Calculator', description: 'This is an online scientific calculator with double-digit precision that supports both button click and keyboard type.', category: 'math', emoji: '🧮', keywords: ['scientific calculator', 'sin', 'cos', 'tan', 'logarithm'], featured: true },
  { slug: 'average-calculator', name: 'Average Calculator', description: 'Free calculator to determine the average, or the arithmetic mean, of a given data set. It also returns the calculation steps, sum, count, and more.', category: 'math', emoji: '📊', keywords: ['average', 'mean', 'arithmetic mean'] },
  { slug: 'percentage-calculator', name: 'Percentage Calculator', description: 'This free percentage calculator computes a number of values involving percentages, including the percentage difference between two given values.', category: 'math', emoji: '%', keywords: ['percentage', 'percent', 'calculation'] },
  { slug: 'percent-error-calculator', name: 'Percent Error Calculator', description: 'This free percent error calculator computes the percentage error between an observed value and the true value of a measurement.', category: 'math', emoji: '🔬', keywords: ['percent error', 'error', 'measurement'] },
  { slug: 'fraction-calculator', name: 'Fraction Calculator', description: 'This free fraction calculator supports fraction addition, subtraction, multiplication, division, and conversion.', category: 'math', emoji: '½', keywords: ['fraction', 'numerator', 'denominator', 'simplify'] },
  { slug: 'binary-calculator', name: 'Binary Calculator', description: 'This free binary calculator can add, subtract, multiply, and divide binary values, as well as convert between binary and decimal values.', category: 'math', emoji: '0️⃣', keywords: ['binary', 'decimal', 'conversion'] },
  { slug: 'hex-calculator', name: 'Hex Calculator', description: 'This free hex calculator can add, subtract, multiply, and divide hexadecimal values, as well as convert between hexadecimal and decimal values.', category: 'math', emoji: '🔡', keywords: ['hexadecimal', 'hex', 'conversion'] },
  { slug: 'root-calculator', name: 'Root Calculator', description: 'This free root calculator determines the roots of numbers, including common roots such as a square root or a cubed root.', category: 'math', emoji: '√', keywords: ['root', 'square root', 'cube root'] },
  { slug: 'exponent-calculator', name: 'Exponent Calculator', description: 'This free exponent calculator determines the result of exponentiation, including expressions that use the irrational number e as a base.', category: 'math', emoji: '🔢', keywords: ['exponent', 'power', 'exponential'] },
  { slug: 'factor-calculator', name: 'Factor Calculator', description: 'This free factor calculator computes the factors and prime factors of a given integer.', category: 'math', emoji: '🔢', keywords: ['factor', 'prime factor', 'divisor'] },
  { slug: 'prime-factorization-calculator', name: 'Prime Factorization Calculator', description: 'This free prime factorization calculator finds the prime factors as well the factor tree of a given integer.', category: 'math', emoji: '🔢', keywords: ['prime factorization', 'factors', 'divisors'] },
  { slug: 'lcm-calculator', name: 'Least Common Multiple Calculator', description: 'This free LCM calculator determines the least common multiple of a given set of numbers.', category: 'math', emoji: '🔢', keywords: ['lcm', 'least common multiple', 'multiples'] },
  { slug: 'gcf-calculator', name: 'Greatest Common Factor Calculator', description: 'This free GCF calculator determines the greatest common factor of a given set of numbers.', category: 'math', emoji: '🔢', keywords: ['gcf', 'gcd', 'greatest common factor'] },
  { slug: 'rounding-calculator', name: 'Rounding Calculator', description: 'Free tool to round numbers to thousands, hundreds, tens, tenths, hundredths, fractions, or many other levels of precision.', category: 'math', emoji: '🔄', keywords: ['rounding', 'precision', 'decimal'] },
  { slug: 'long-division-calculator', name: 'Long Division Calculator', description: 'Free calculator that determines the quotient and remainder of a long division problem and provides calculation steps.', category: 'math', emoji: '÷', keywords: ['long division', 'division', 'quotient', 'remainder'] },
  { slug: 'log-calculator', name: 'Log Calculator', description: 'This free log calculator solves for the unknown portions of a logarithmic expression using base e, 2, 10, or any other desired base.', category: 'math', emoji: 'ln', keywords: ['logarithm', 'log', 'natural log'] },
  { slug: 'standard-deviation-calculator', name: 'Standard Deviation Calculator', description: 'This free standard deviation calculator computes the standard deviation, variance, mean, sum, and error margin of a given data set.', category: 'math', emoji: 'σ', keywords: ['standard deviation', 'variance', 'statistics'] },
  { slug: 'statistics-calculator', name: 'Statistics Calculator', description: 'This statistics calculator computes a number of common statistical values including standard deviation, mean, sum, geometric mean, and more.', category: 'math', emoji: '📊', keywords: ['statistics', 'mean', 'median', 'average'] },
  { slug: 'mean-median-mode-calculator', name: 'Mean/Median/Mode Calculator', description: 'This calculator determines the mean, median, mode, and range of a given data set.', category: 'math', emoji: '📊', keywords: ['mean', 'median', 'mode', 'range'] },
  { slug: 'random-number-generator', name: 'Random Number Generator', description: 'Two free random number generators that work in user-defined min and max range. Both random integers and decimal numbers can be generated with high precision.', category: 'math', emoji: '🎲', keywords: ['random number', 'random', 'generator'] },
  { slug: 'number-sequence-calculator', name: 'Number Sequence Calculator', description: 'This free number sequence calculator can determine the terms of the arithmetic, geometric, or Fibonacci sequence.', category: 'math', emoji: '🔢', keywords: ['sequence', 'arithmetic', 'geometric'] },
  { slug: 'probability-calculator', name: 'Probability Calculator', description: 'This calculator can calculate the probability of two events, as well as that of a normal distribution.', category: 'math', emoji: '🎯', keywords: ['probability', 'statistics', 'likelihood'] },
  { slug: 'permutation-combination-calculator', name: 'Permutation and Combination Calculator', description: 'This free calculator can compute the number of possible permutations and combinations when selecting r elements from a set of n elements.', category: 'math', emoji: '🔀', keywords: ['permutation', 'combination', 'probability'] },
  { slug: 'z-score-calculator', name: 'Z-score Calculator', description: 'Calculator to find out the z-score of a normal distribution, convert between z-score and probability, and find the probability between 2 z-scores.', category: 'math', emoji: 'z', keywords: ['z-score', 'statistics', 'normal distribution'] },
  { slug: 'p-value-calculator', name: 'P-value Calculator', description: 'Calculator to compute p-value from Z-score or Z-score from p-value for a normal distribution.', category: 'math', emoji: '📊', keywords: ['p-value', 'statistics', 'z-score'] },
  { slug: 'confidence-interval-calculator', name: 'Confidence Interval Calculator', description: 'Calculator to compute the confidence interval or margin of error of a sample based on the desired confidence level.', category: 'math', emoji: '📏', keywords: ['confidence interval', 'statistics', 'margin of error'] },
  { slug: 'sample-size-calculator', name: 'Sample Size Calculator', description: 'This free sample size calculator determines the sample size required to meet a given set of constraints.', category: 'math', emoji: '📊', keywords: ['sample size', 'statistics', 'confidence'] },
  { slug: 'ratio-calculator', name: 'Ratio Calculator', description: 'This ratio calculator solves ratios, scales ratios, or finds the missing value in a set of ratios.', category: 'math', emoji: '⚖️', keywords: ['ratio', 'proportion', 'scale'] },
  { slug: 'distance-calculator', name: 'Distance Calculator', description: 'Free calculators to compute the distance between two coordinates on a 2D plane or 3D space.', category: 'math', emoji: '📍', keywords: ['distance', 'coordinates', 'distance formula'] },
  { slug: 'area-calculator', name: 'Area Calculator', description: 'This area calculator determines the area of a number of common shapes, including rectangle, triangle, trapezoid, circle, sector, ellipse, and parallelogram.', category: 'math', emoji: '⬜', keywords: ['area', 'square', 'rectangle', 'circle'] },
  { slug: 'circle-calculator', name: 'Circle Calculator', description: 'This calculator computes the values of typical circle parameters such as radius, diameter, circumference, and area.', category: 'math', emoji: '⭕', keywords: ['circle', 'radius', 'circumference', 'area'] },
  { slug: 'volume-calculator', name: 'Volume Calculator', description: 'This free volume calculator computes the volumes of common shapes, including sphere, cone, cube, cylinder, and more.', category: 'math', emoji: '📦', keywords: ['volume', 'capacity', 'shapes'] },
  { slug: 'surface-area-calculator', name: 'Surface Area Calculator', description: 'This calculator computes the surface area of a number of common shapes, including sphere, cone, cube, cylinder, and more.', category: 'math', emoji: '🔲', keywords: ['surface area', 'geometry', 'shapes'] },
  { slug: 'triangle-calculator', name: 'Triangle Calculator', description: 'This free triangle calculator computes the edges, angles, area, height, perimeter, and median of the resulting triangle.', category: 'math', emoji: '📐', keywords: ['triangle', 'geometry', 'angle'] },
  { slug: 'pythagorean-theorem-calculator', name: 'Pythagorean Theorem Calculator', description: 'Pythagorean Theorem calculator to find out the unknown length of a right triangle.', category: 'math', emoji: '📐', keywords: ['pythagorean theorem', 'right triangle', 'hypotenuse'] },
  { slug: 'quadratic-formula-calculator', name: 'Quadratic Formula Calculator', description: 'This free quadratic formula calculator solves the quadratic formula given values for a, b, and c.', category: 'math', emoji: '📉', keywords: ['quadratic', 'quadratic formula', 'equation'] },
  { slug: 'slope-calculator', name: 'Slope Calculator', description: 'This slope calculator solves for parameters involving slope and the equation of a line.', category: 'math', emoji: '↗️', keywords: ['slope', 'gradient', 'linear'] },
  { slug: 'matrix-calculator', name: 'Matrix Calculator', description: 'Free calculator to perform matrix operations on one or two matrices including addition, subtraction, multiplication, determinant, inverse, or transpose.', category: 'math', emoji: '🔲', keywords: ['matrix', 'matrices', 'determinant'] },
  { slug: 'scientific-notation-calculator', name: 'Scientific Notation Calculator', description: 'Online tool to convert between number formats including scientific notation, E-notation, engineering notation, and real numbers.', category: 'math', emoji: '🔬', keywords: ['scientific notation', 'exponent', 'power of 10'] },
  { slug: 'big-number-calculator', name: 'Big Number Calculator', description: 'This free big number calculator can perform calculations involving very large integers or decimals at a high level of precision.', category: 'math', emoji: '∞', keywords: ['big number', 'large number', 'precision'] },
  { slug: 'basic-calculator', name: 'Basic Calculator', description: 'This free online calculator can be used for basic computations such as addition, subtraction, multiplication, division, and square roots.', category: 'math', emoji: '🧮', keywords: ['addition', 'subtraction', 'multiplication', 'division'] },
  { slug: 'molarity-calculator', name: 'Molarity Calculator', description: 'This free molarity calculator determines any of the four variables in the molarity equation given the other three.', category: 'math', emoji: '🧪', keywords: ['molarity', 'chemistry', 'concentration'] },
  { slug: 'molecular-weight-calculator', name: 'Molecular Weight Calculator', description: 'This molecular weight calculator can determine the molecular weight or molar mass of a molecule based on its formula.', category: 'math', emoji: '🧬', keywords: ['molecular weight', 'molar mass', 'chemistry'] },
  { slug: 'density-calculator', name: 'Density Calculator', description: 'This free density calculator determines any of the three variables in the density equation given the other two.', category: 'math', emoji: '⚛️', keywords: ['density', 'mass', 'volume'] },
  { slug: 'half-life-calculator', name: 'Half-Life Calculator', description: 'This calculator computes any of the values in the half-life formula given the rest values.', category: 'math', emoji: '☢️', keywords: ['half-life', 'decay', 'exponential'] },
  { slug: 'ohms-law-calculator', name: "Ohm's Law Calculator", description: "This free Ohm's Law calculator solves for any of the variables in the Ohm's Law equation using various units of measurement.", category: 'math', emoji: '⚡', keywords: ["ohm's law", 'electricity', 'voltage'] },

  // DATE & TIME CALCULATORS (15+)
  { slug: 'age-calculator', name: 'Age Calculator', description: 'This free age calculator computes age in terms of years, months, weeks, days, hours, minutes, and seconds, given a date of birth.', category: 'utility', emoji: '🎂', keywords: ['age', 'birthday', 'date of birth'], featured: true },
  { slug: 'date-calculator', name: 'Date Calculator', description: 'This free date calculator computes the difference between two dates. It can also add to or subtract from a date.', category: 'utility', emoji: '📅', keywords: ['date', 'days between', 'date calculation'] },
  { slug: 'time-calculator', name: 'Time Calculator', description: 'This free time calculator can add or subtract time values in terms of number of days, hours, minutes, or seconds.', category: 'utility', emoji: '⏰', keywords: ['time', 'hours', 'minutes', 'duration'] },
  { slug: 'time-duration-calculator', name: 'Time Duration Calculator', description: 'Free calculator to get the number of hours, minutes, and seconds between two times.', category: 'utility', emoji: '⏳', keywords: ['time duration', 'hours between', 'time difference'] },
  { slug: 'hours-calculator', name: 'Hours Calculator', description: 'This hours calculator computes the number of hours and minutes between two times.', category: 'utility', emoji: '⏱️', keywords: ['hours', 'work hours', 'time tracking'] },
  { slug: 'day-counter', name: 'Day Counter', description: 'Free day counter to calculate the number of days between two dates, including working days, weekends, and holidays.', category: 'utility', emoji: '📆', keywords: ['day counter', 'days between', 'working days'] },
  { slug: 'day-of-week-calculator', name: 'Day of the Week Calculator', description: 'This weekday calculator can find the day of the week of any date and provides the calendar of the month.', category: 'utility', emoji: '📅', keywords: ['day of week', 'weekday', 'calendar'] },
  { slug: 'time-zone-calculator', name: 'Time Zone Calculator', description: 'This calculator converts between different time zones around the world using the GMT format.', category: 'utility', emoji: '🌍', keywords: ['time zone', 'gmt', 'world time'] },
  { slug: 'sleep-calculator', name: 'Sleep Calculator', description: 'Calculator to compute the time to wake up or go to bed based on sleep cycle or duration of sleep required.', category: 'utility', emoji: '😴', keywords: ['sleep', 'sleep cycles', 'rest'] },
  { slug: 'period-calculator', name: 'Period Calculator', description: 'This free calculator estimates days in the future during which a person is expected to undergo their period.', category: 'utility', emoji: '📅', keywords: ['period', 'menstrual', 'cycle'] },

  // UTILITY & OTHER (40+)
  { slug: 'tip-calculator', name: 'Tip Calculator', description: 'This free tip calculator computes tip amounts for various situations. It can also calculate the tip amount split between a given number of people.', category: 'utility', emoji: '🍽️', keywords: ['tip', 'gratuity', 'bill'], featured: true },
  { slug: 'conversion-calculator', name: 'Conversion Calculator', description: 'This free conversion calculator converts between common units of length, temperature, area, volume, weight, and time.', category: 'utility', emoji: '🔄', keywords: ['conversion', 'units', 'measurement'] },
  { slug: 'speed-calculator', name: 'Speed Calculator', description: 'This free speed calculator computes any of the three variables in the speed distance time equation given the other two.', category: 'utility', emoji: '🏎️', keywords: ['speed', 'distance', 'time', 'velocity'] },
  { slug: 'weight-calculator', name: 'Weight Calculator', description: 'This free weight calculator converts between common units of weight and mass.', category: 'utility', emoji: '⚖️', keywords: ['weight', 'kg to lbs', 'conversion'] },
  { slug: 'mass-calculator', name: 'Mass Calculator', description: 'This free mass calculator calculates mass, given density and volume, using various standard units of measurement.', category: 'utility', emoji: '⚖️', keywords: ['mass', 'weight', 'density', 'volume'] },
  { slug: 'fuel-cost-calculator', name: 'Fuel Cost Calculator', description: 'This free fuel cost calculator estimates the fuel cost of a trip based on fuel efficiency, distance, and gas price.', category: 'utility', emoji: '⛽', keywords: ['fuel cost', 'gas cost', 'road trip'] },
  { slug: 'gas-mileage-calculator', name: 'Gas Mileage Calculator', description: 'This free gas mileage calculator estimates gas mileage based on odometer readings, gas price per gallon, and tank amount.', category: 'utility', emoji: '🚘', keywords: ['gas mileage', 'mpg', 'fuel efficiency'] },
  { slug: 'mileage-calculator', name: 'Mileage Calculator', description: 'This mileage calculator estimates the number of driving miles between two locations in the United States.', category: 'utility', emoji: '🗺️', keywords: ['mileage', 'distance', 'travel'] },
  { slug: 'btu-calculator', name: 'BTU Calculator', description: 'Two free calculators estimate the number of BTUs needed to cool or heat a room or house.', category: 'utility', emoji: '❄️', keywords: ['btu', 'heating', 'cooling'] },
  { slug: 'electricity-calculator', name: 'Electricity Calculator', description: 'Free electricity calculator to estimate electricity usage as well as cost based on power requirements.', category: 'utility', emoji: '💡', keywords: ['electricity', 'kwh', 'power consumption'] },
  { slug: 'bandwidth-calculator', name: 'Bandwidth Calculator', description: 'This calculator can convert between units of bandwidth, estimate download or upload times.',category: 'utility', emoji: '📡', keywords: ['bandwidth', 'download', 'upload'] },
  { slug: 'password-generator', name: 'Password Generator', description: 'A random password generator to create strong and secure passwords.', category: 'utility', emoji: '🔐', keywords: ['password', 'generator', 'security'] },
  { slug: 'ip-subnet-calculator', name: 'IP Subnet Calculator', description: 'This IP subnet calculator covers both IPv4 and IPv6 protocols, providing information such as IP address, network address, subnet mask.',category: 'utility', emoji: '🌐', keywords: ['ip subnet', 'network', 'cidr'] },
  { slug: 'gpa-calculator', name: 'GPA Calculator', description: 'This GPA calculator computes GPA and generates a report based on course credits and achieved grade.', category: 'utility', emoji: '🎓', keywords: ['gpa', 'grade point average', 'grades'] },
  { slug: 'grade-calculator', name: 'Grade Calculator', description: 'This free grade calculator can calculate a weighted average grade accepting both numerical and letter grades.', category: 'utility', emoji: '📝', keywords: ['grade', 'average', 'score'] },
  { slug: 'concrete-calculator', name: 'Concrete Calculator', description: 'This free concrete calculator estimates the amount of concrete necessary for a project.', category: 'utility', emoji: '🏗️', keywords: ['concrete', 'cement', 'cubic yards'] },
  { slug: 'roofing-calculator', name: 'Roofing Calculator', description: 'This free roofing calculator estimates the area of a roof and materials required.', category: 'utility', emoji: '🏠', keywords: ['roofing', 'roof', 'shingles'] },
  { slug: 'tile-calculator', name: 'Tile Calculator', description: 'This calculator estimates the number of tiles needed to cover an area such as a floor, wall, or roof.', category: 'utility', emoji: '🟫', keywords: ['tile', 'flooring', 'bathroom'] },
  { slug: 'square-footage-calculator', name: 'Square Footage Calculator', description: 'This free calculator estimates the square footage of a property and accounts for various common lot shapes.', category: 'utility', emoji: '📐', keywords: ['square footage', 'area', 'room size'] },
  { slug: 'mulch-calculator', name: 'Mulch Calculator', description: 'This free mulch calculator estimates the total amount of mulch needed to cover an area such as a garden.', category: 'utility', emoji: '🌱', keywords: ['mulch', 'garden', 'area coverage'] },
  { slug: 'gravel-calculator', name: 'Gravel Calculator', description: 'This free gravel calculator estimates the amount of gravel needed to cover an area and can also estimate the cost.', category: 'utility', emoji: '🪨', keywords: ['gravel', 'driveway', 'landscaping'] },
  { slug: 'stair-calculator', name: 'Stair Calculator', description: 'This stair calculator computes stair parameters such as rise, total run, angle, and stringer length.', category: 'utility', emoji: '🪜', keywords: ['stair', 'stairs', 'construction'] },
  { slug: 'dew-point-calculator', name: 'Dew Point Calculator', description: 'This free dew point calculator calculates dew point, relative humidity, or air temperature.',category: 'utility', emoji: '💧', keywords: ['dew point', 'humidity', 'temperature'] },
  { slug: 'heat-index-calculator', name: 'Heat Index Calculator', description: 'This calculator estimates heat index temperature felt by the human body based on actual measured air temperature with humidity level.',category: 'utility', emoji: '🌡️', keywords: ['heat index', 'feels like', 'humidity'] },
  { slug: 'wind-chill-calculator', name: 'Wind Chill Calculator', description: 'This calculator estimates wind chill temperature based on air temperature and wind speed.', category: 'utility', emoji: '🌬️', keywords: ['wind chill', 'temperature', 'weather'] },
  { slug: 'voltage-drop-calculator', name: 'Voltage Drop Calculator', description: 'This free voltage drop calculator estimates the voltage drop of an electrical circuit based on wire size, distance, and anticipated load current.', category: 'utility', emoji: '⚡', keywords: ['voltage drop', 'electrical', 'circuit'] },
  { slug: 'resistor-calculator', name: 'Resistor Calculator', description: 'This resistor calculator converts the ohm value and tolerance based on resistor color codes.', category: 'utility', emoji: '⚡', keywords: ['resistor', 'ohm', 'electronics'] },
  { slug: 'tire-size-calculator', name: 'Tire Size Calculator', description: 'Free calculator to find the dimensions of a tire based on its code and helps in choosing alternative tire sizes.', category: 'utility', emoji: '🔄', keywords: ['tire', 'tire size', 'wheel'] },
  { slug: 'horsepower-calculator', name: 'Horsepower Calculator', description: 'This free calculator determines horsepower as a unit of power and provides a converter for common units of power.', category: 'utility', emoji: '🐎', keywords: ['horsepower', 'power', 'energy'] },
  { slug: 'engine-horsepower-calculator', name: 'Engine Horsepower Calculator', description: 'This free engine horsepower calculator estimates vehicle engine horsepower.', category: 'utility', emoji: '🏎️', keywords: ['engine horsepower', 'dyno', 'engine'] },
  { slug: 'love-calculator', name: 'Love Calculator', description: 'This free calculator evaluates compatibility based on two names, returning a score from 0% to 100%.', category: 'utility', emoji: '❤️', keywords: ['love', 'compatibility', 'match'] },
  { slug: 'gdp-calculator', name: 'GDP Calculator', description: 'This free GDP calculator computes GDP using both the expenditure approach and the resource cost-income approach.', category: 'utility', emoji: '📊', keywords: ['gdp', 'gross domestic product', 'economy'] },
  { slug: 'golf-handicap-calculator', name: 'Golf Handicap Calculator', description: 'Two free calculators for computing a golf player\'s course handicap and the World Handicap System (WHS) handicap index.', category: 'utility', emoji: '⛳', keywords: ['golf', 'handicap', 'golf score'] },
  { slug: 'roman-numeral-converter', name: 'Roman Numeral Converter', description: 'This free converter converts between Arabic numbers and Roman numerals.',category: 'utility', emoji: 'Ⅻ', keywords: ['roman numeral', 'roman', 'convert'] },
  { slug: 'base64-calculator', name: 'Base64 Encode/Decode', description: 'This free online tool can Base64-encode or decode text, images, and files directly in the browser.', category: 'utility', emoji: '💻', keywords: ['base64', 'encode', 'decode'] },
  { slug: 'url-encoder', name: 'URL Encode/Decode', description: 'This free online tool can encode or decode data to and from a URL-compatible format.', category: 'utility', emoji: '🔗', keywords: ['url encode', 'url decode', 'encoding'] },
  { slug: 'shoe-size-calculator', name: 'Shoe Size Conversion', description: 'This free tool converts between shoe sizes used in the U.S., Canada, UK, India, EU, Japan, Mexico, and China.', category: 'utility', emoji: '👟', keywords: ['shoe size', 'footwear', 'measurement'] },
  { slug: 'dice-roller', name: 'Dice Roller', description: 'Online virtual dice roller that is capable of simultaneously rolling up to 100 dice randomly.',category: 'utility', emoji: '🎲', keywords: ['dice', 'roller', 'random'] },
  { slug: 'time-card-calculator', name: 'Time Card Calculator', description: 'This free time card calculator generates weekly time reports based on provided work times and hourly rates.', category: 'utility', emoji: '🗂️', keywords: ['time card', 'work hours', 'payroll'] },
];

// Ensure one canonical calculator per slug across the app.
const seenSlugs = new Set<string>();
export const calculators: Calculator[] = rawCalculators.filter((calc) => {
  if (seenSlugs.has(calc.slug)) return false;
  seenSlugs.add(calc.slug);
  return true;
});

export function getCalculatorBySlug(slug: string): Calculator | undefined {
  return calculators.find(c => c.slug === slug);
}

export function getCalculatorsByCategory(category: string): Calculator[] {
  return calculators.filter(c => c.category === category);
}

export function getFeaturedCalculators(): Calculator[] {
  return calculators.filter(c => c.featured);
}

export function searchCalculators(query: string): Calculator[] {
  const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').replace(/\s+/g, ' ').trim();
  const stopWords = new Set(['calculator', 'calculators', 'calc', 'tool', 'tools', 'online', 'free']);
  const q = normalize(query);
  if (!q) return calculators;

  const rawTokens = q.split(' ').filter(Boolean);
  const meaningfulTokens = rawTokens.filter(token => !stopWords.has(token));
  const tokens = meaningfulTokens.length > 0 ? meaningfulTokens : rawTokens;

  return calculators.filter(c => {
    const nameWords = normalize(c.name).split(' ').filter(Boolean);
    return tokens.every(token => nameWords.some(word => word.startsWith(token)));
  });
}
