export interface Calculator {
  slug: string;
  name: string;
  description: string;
  category: string;
  emoji: string;
  keywords: string[];
  featured?: boolean;
}

export const calculators: Calculator[] = [
  // FINANCIAL CALCULATORS
  { slug: 'mortgage-calculator', name: 'Mortgage Calculator', description: 'Calculate monthly mortgage payments, total interest, and loan amortization.', category: 'financial', emoji: '🏠', keywords: ['mortgage', 'home loan', 'house payment', 'monthly payment'], featured: true },
  { slug: 'loan-calculator', name: 'Loan Calculator', description: 'Calculate loan payments, interest rates, and repayment schedules.', category: 'financial', emoji: '💳', keywords: ['loan', 'payment', 'interest', 'borrow'], featured: true },
  { slug: 'auto-loan-calculator', name: 'Auto Loan Calculator', description: 'Calculate car loan payments and total cost of vehicle financing.', category: 'financial', emoji: '🚗', keywords: ['auto loan', 'car loan', 'vehicle payment'] },
  { slug: 'interest-calculator', name: 'Interest Calculator', description: 'Calculate simple and compound interest on any amount.', category: 'financial', emoji: '📈', keywords: ['interest', 'savings', 'investment'] },
  { slug: 'payment-calculator', name: 'Payment Calculator', description: 'Calculate monthly payment amounts for any loan or mortgage.', category: 'financial', emoji: '💰', keywords: ['payment', 'monthly', 'loan payment'] },
  { slug: 'retirement-calculator', name: 'Retirement Calculator', description: 'Plan your retirement savings and estimate retirement income.', category: 'financial', emoji: '🏖️', keywords: ['retirement', 'savings', '401k', 'pension'] },
  { slug: 'amortization-calculator', name: 'Amortization Calculator', description: 'Generate complete loan amortization schedules.', category: 'financial', emoji: '📊', keywords: ['amortization', 'loan schedule', 'payment schedule'] },
  { slug: 'investment-calculator', name: 'Investment Calculator', description: 'Calculate investment returns, growth, and future value.', category: 'financial', emoji: '📉', keywords: ['investment', 'returns', 'growth', 'stocks'] },
  { slug: 'currency-calculator', name: 'Currency Calculator', description: 'Convert between different world currencies.', category: 'financial', emoji: '💱', keywords: ['currency', 'exchange', 'forex', 'convert'] },
  { slug: 'inflation-calculator', name: 'Inflation Calculator', description: 'Calculate the effect of inflation on purchasing power.', category: 'financial', emoji: '💹', keywords: ['inflation', 'purchasing power', 'cpi'] },
  { slug: 'finance-calculator', name: 'Finance Calculator', description: 'Comprehensive financial calculations for any scenario.', category: 'financial', emoji: '🏦', keywords: ['finance', 'financial', 'calculator'] },
  { slug: 'mortgage-payoff-calculator', name: 'Mortgage Payoff Calculator', description: 'Calculate how to pay off your mortgage faster.', category: 'financial', emoji: '🏡', keywords: ['mortgage payoff', 'early payoff', 'extra payment'] },
  { slug: 'income-tax-calculator', name: 'Income Tax Calculator', description: 'Estimate your federal and state income tax liability.', category: 'financial', emoji: '🧾', keywords: ['income tax', 'federal tax', 'state tax', 'tax return'] },
  { slug: 'compound-interest-calculator', name: 'Compound Interest Calculator', description: 'Calculate compound interest growth over time.', category: 'financial', emoji: '📐', keywords: ['compound interest', 'savings growth', 'interest'], featured: true },
  { slug: 'salary-calculator', name: 'Salary Calculator', description: 'Convert salary to hourly rate or different pay periods.', category: 'financial', emoji: '💼', keywords: ['salary', 'hourly', 'annual', 'pay'] },
  { slug: '401k-calculator', name: '401K Calculator', description: 'Calculate 401k contributions and retirement savings growth.', category: 'financial', emoji: '🏛️', keywords: ['401k', 'retirement', 'contribution', 'employer match'] },
  { slug: 'interest-rate-calculator', name: 'Interest Rate Calculator', description: 'Find the interest rate for a loan or investment.', category: 'financial', emoji: '🔢', keywords: ['interest rate', 'apr', 'apy'] },
  { slug: 'sales-tax-calculator', name: 'Sales Tax Calculator', description: 'Calculate sales tax amount and total price after tax.', category: 'financial', emoji: '🛒', keywords: ['sales tax', 'tax rate', 'total price'] },
  { slug: 'house-affordability-calculator', name: 'House Affordability Calculator', description: 'Find out how much house you can afford based on income.', category: 'financial', emoji: '🏘️', keywords: ['house affordability', 'home buying', 'mortgage qualify'] },
  { slug: 'savings-calculator', name: 'Savings Calculator', description: 'Calculate savings growth with regular contributions.', category: 'financial', emoji: '🐷', keywords: ['savings', 'save money', 'savings account'] },
  { slug: 'rent-calculator', name: 'Rent Calculator', description: 'Determine how much rent you can afford.', category: 'financial', emoji: '🏢', keywords: ['rent', 'rental', 'apartment'] },
  { slug: 'marriage-tax-calculator', name: 'Marriage Tax Calculator', description: 'Calculate the marriage tax penalty or bonus.', category: 'financial', emoji: '💍', keywords: ['marriage tax', 'married filing', 'tax penalty'] },
  { slug: 'estate-tax-calculator', name: 'Estate Tax Calculator', description: 'Estimate estate tax liability for inheritance planning.', category: 'financial', emoji: '🏛️', keywords: ['estate tax', 'inheritance', 'estate planning'] },
  { slug: 'pension-calculator', name: 'Pension Calculator', description: 'Calculate pension benefits and retirement income.', category: 'financial', emoji: '👴', keywords: ['pension', 'retirement income', 'defined benefit'] },
  { slug: 'social-security-calculator', name: 'Social Security Calculator', description: 'Estimate your Social Security retirement benefits.', category: 'financial', emoji: '🤝', keywords: ['social security', 'ssa', 'benefits', 'retirement'] },
  { slug: 'annuity-calculator', name: 'Annuity Calculator', description: 'Calculate annuity payments and present/future value.', category: 'financial', emoji: '📋', keywords: ['annuity', 'annuity payment', 'retirement'] },
  { slug: 'annuity-payout-calculator', name: 'Annuity Payout Calculator', description: 'Calculate annuity payout amounts and duration.', category: 'financial', emoji: '💸', keywords: ['annuity payout', 'income stream', 'retirement'] },
  { slug: 'credit-card-calculator', name: 'Credit Card Calculator', description: 'Calculate credit card interest and payoff time.', category: 'financial', emoji: '💳', keywords: ['credit card', 'interest', 'minimum payment', 'payoff'] },
  { slug: 'credit-cards-payoff-calculator', name: 'Credit Cards Payoff Calculator', description: 'Create a plan to pay off multiple credit cards.', category: 'financial', emoji: '✂️', keywords: ['credit card payoff', 'debt', 'multiple cards'] },
  { slug: 'debt-payoff-calculator', name: 'Debt Payoff Calculator', description: 'Create a strategy to pay off your debt faster.', category: 'financial', emoji: '⛓️', keywords: ['debt payoff', 'debt free', 'payoff strategy'] },
  { slug: 'debt-consolidation-calculator', name: 'Debt Consolidation Calculator', description: 'Calculate savings from consolidating multiple debts.', category: 'financial', emoji: '🔗', keywords: ['debt consolidation', 'combine debt', 'lower rate'] },
  { slug: 'repayment-calculator', name: 'Repayment Calculator', description: 'Calculate loan repayment schedules and options.', category: 'financial', emoji: '↩️', keywords: ['repayment', 'loan repayment', 'pay back'] },
  { slug: 'student-loan-calculator', name: 'Student Loan Calculator', description: 'Calculate student loan payments and total repayment.', category: 'financial', emoji: '🎓', keywords: ['student loan', 'college debt', 'education loan'] },
  { slug: 'college-cost-calculator', name: 'College Cost Calculator', description: 'Estimate the total cost of college education.', category: 'financial', emoji: '📚', keywords: ['college cost', 'tuition', 'education cost'] },
  { slug: 'simple-interest-calculator', name: 'Simple Interest Calculator', description: 'Calculate simple interest for loans and savings.', category: 'financial', emoji: '➕', keywords: ['simple interest', 'principal', 'rate', 'time'] },
  { slug: 'cd-calculator', name: 'CD Calculator', description: 'Calculate certificate of deposit earnings.', category: 'financial', emoji: '💿', keywords: ['cd', 'certificate of deposit', 'savings', 'apy'] },
  { slug: 'bond-calculator', name: 'Bond Calculator', description: 'Calculate bond prices, yields, and returns.', category: 'financial', emoji: '📜', keywords: ['bond', 'yield', 'coupon', 'maturity'] },
  { slug: 'mutual-fund-calculator', name: 'Mutual Fund Calculator', description: 'Calculate mutual fund returns and growth.', category: 'financial', emoji: '📊', keywords: ['mutual fund', 'fund returns', 'investment'] },
  { slug: 'roth-ira-calculator', name: 'Roth IRA Calculator', description: 'Calculate Roth IRA contributions and tax-free growth.', category: 'financial', emoji: '🌱', keywords: ['roth ira', 'tax free', 'retirement savings'] },
  { slug: 'ira-calculator', name: 'IRA Calculator', description: 'Calculate IRA contributions and tax-deferred growth.', category: 'financial', emoji: '💰', keywords: ['ira', 'traditional ira', 'retirement savings'] },
  { slug: 'rmd-calculator', name: 'RMD Calculator', description: 'Calculate Required Minimum Distributions from retirement accounts.', category: 'financial', emoji: '🔄', keywords: ['rmd', 'required minimum distribution', 'retirement withdrawal'] },
  { slug: 'vat-calculator', name: 'VAT Calculator', description: 'Calculate VAT (Value Added Tax) for purchases.', category: 'financial', emoji: '🧮', keywords: ['vat', 'value added tax', 'uk tax', 'europe tax'] },
  { slug: 'cash-back-calculator', name: 'Cash Back Calculator', description: 'Compare cash back vs low interest credit card offers.', category: 'financial', emoji: '💵', keywords: ['cash back', 'rewards', 'credit card'] },
  { slug: 'auto-lease-calculator', name: 'Auto Lease Calculator', description: 'Calculate monthly car lease payments and total cost.', category: 'financial', emoji: '🚙', keywords: ['auto lease', 'car lease', 'lease payment'] },
  { slug: 'depreciation-calculator', name: 'Depreciation Calculator', description: 'Calculate asset depreciation using various methods.', category: 'financial', emoji: '📉', keywords: ['depreciation', 'asset', 'straight line', 'macrs'] },
  { slug: 'average-return-calculator', name: 'Average Return Calculator', description: 'Calculate average annual return on investments.', category: 'financial', emoji: '📈', keywords: ['average return', 'annual return', 'cagr'] },
  { slug: 'margin-calculator', name: 'Margin Calculator', description: 'Calculate profit margins, markup, and selling price.', category: 'financial', emoji: '💹', keywords: ['margin', 'profit margin', 'markup', 'gross margin'] },
  { slug: 'discount-calculator', name: 'Discount Calculator', description: 'Calculate discounts and final prices after discounts.', category: 'financial', emoji: '🏷️', keywords: ['discount', 'sale price', 'percent off'] },
  { slug: 'business-loan-calculator', name: 'Business Loan Calculator', description: 'Calculate business loan payments and terms.', category: 'financial', emoji: '🏢', keywords: ['business loan', 'commercial loan', 'sba loan'] },
  { slug: 'debt-to-income-ratio-calculator', name: 'Debt-to-Income Ratio Calculator', description: 'Calculate your debt-to-income ratio for loan qualification.', category: 'financial', emoji: '⚖️', keywords: ['debt to income', 'dti ratio', 'mortgage qualify'] },
  { slug: 'real-estate-calculator', name: 'Real Estate Calculator', description: 'Calculate real estate investment returns and metrics.', category: 'financial', emoji: '🏙️', keywords: ['real estate', 'property', 'investment', 'roi'] },
  { slug: 'take-home-paycheck-calculator', name: 'Take-Home-Paycheck Calculator', description: 'Calculate your net take-home pay after all deductions.', category: 'financial', emoji: '💵', keywords: ['take home pay', 'net pay', 'paycheck', 'deductions'] },
  { slug: 'personal-loan-calculator', name: 'Personal Loan Calculator', description: 'Calculate personal loan payments and total cost.', category: 'financial', emoji: '🤝', keywords: ['personal loan', 'unsecured loan', 'loan payment'] },
  { slug: 'boat-loan-calculator', name: 'Boat Loan Calculator', description: 'Calculate boat and marine loan payments.', category: 'financial', emoji: '⛵', keywords: ['boat loan', 'marine loan', 'watercraft'] },
  { slug: 'lease-calculator', name: 'Lease Calculator', description: 'Calculate lease payments for any type of lease.', category: 'financial', emoji: '📝', keywords: ['lease', 'lease payment', 'rent to own'] },
  { slug: 'refinance-calculator', name: 'Refinance Calculator', description: 'Calculate savings from refinancing your mortgage or loan.', category: 'financial', emoji: '🔄', keywords: ['refinance', 'refi', 'lower rate', 'break even'] },
  { slug: 'budget-calculator', name: 'Budget Calculator', description: 'Create and manage a personal or household budget.', category: 'financial', emoji: '📒', keywords: ['budget', 'personal budget', 'spending', 'income'] },
  { slug: 'rental-property-calculator', name: 'Rental Property Calculator', description: 'Analyze rental property investment returns and cash flow.', category: 'financial', emoji: '🏠', keywords: ['rental property', 'cash flow', 'cap rate', 'roi'] },
  { slug: 'irr-calculator', name: 'IRR Calculator', description: 'Calculate Internal Rate of Return for investments.', category: 'financial', emoji: '📊', keywords: ['irr', 'internal rate of return', 'investment'] },
  { slug: 'roi-calculator', name: 'ROI Calculator', description: 'Calculate Return on Investment for any investment.', category: 'financial', emoji: '💰', keywords: ['roi', 'return on investment', 'profit'] },
  { slug: 'apr-calculator', name: 'APR Calculator', description: 'Calculate Annual Percentage Rate for loans.', category: 'financial', emoji: '🔢', keywords: ['apr', 'annual percentage rate', 'loan cost'] },
  { slug: 'fha-loan-calculator', name: 'FHA Loan Calculator', description: 'Calculate FHA loan payments with MIP insurance.', category: 'financial', emoji: '🏠', keywords: ['fha loan', 'fha mortgage', 'government loan'] },
  { slug: 'va-mortgage-calculator', name: 'VA Mortgage Calculator', description: 'Calculate VA home loan payments for veterans.', category: 'financial', emoji: '🎖️', keywords: ['va loan', 'veteran mortgage', 'va mortgage'] },
  { slug: 'home-equity-loan-calculator', name: 'Home Equity Loan Calculator', description: 'Calculate home equity loan payments and borrowing power.', category: 'financial', emoji: '🏠', keywords: ['home equity', 'equity loan', 'second mortgage'] },
  { slug: 'heloc-calculator', name: 'HELOC Calculator', description: 'Calculate HELOC payments and available credit.', category: 'financial', emoji: '🏡', keywords: ['heloc', 'home equity line', 'credit line'] },
  { slug: 'down-payment-calculator', name: 'Down Payment Calculator', description: 'Calculate down payment needed for a home purchase.', category: 'financial', emoji: '💵', keywords: ['down payment', 'home purchase', 'closing costs'] },
  { slug: 'rent-vs-buy-calculator', name: 'Rent vs. Buy Calculator', description: 'Compare the financial impact of renting vs. buying a home.', category: 'financial', emoji: '⚖️', keywords: ['rent vs buy', 'home buying', 'financial comparison'] },
  { slug: 'payback-period-calculator', name: 'Payback Period Calculator', description: 'Calculate the payback period for an investment.', category: 'financial', emoji: '⏱️', keywords: ['payback period', 'investment', 'break even'] },
  { slug: 'present-value-calculator', name: 'Present Value Calculator', description: 'Calculate the present value of future cash flows.', category: 'financial', emoji: '📅', keywords: ['present value', 'pv', 'discounted cash flow'] },
  { slug: 'future-value-calculator', name: 'Future Value Calculator', description: 'Calculate the future value of an investment.', category: 'financial', emoji: '🔮', keywords: ['future value', 'fv', 'compound growth'] },
  { slug: 'commission-calculator', name: 'Commission Calculator', description: 'Calculate sales commission amounts and rates.', category: 'financial', emoji: '💼', keywords: ['commission', 'sales commission', 'agent fee'] },
  { slug: 'mortgage-calculator-uk', name: 'Mortgage Calculator UK', description: 'Calculate UK mortgage payments and costs.', category: 'financial', emoji: '🇬🇧', keywords: ['uk mortgage', 'british mortgage', 'stamp duty'] },
  { slug: 'canadian-mortgage-calculator', name: 'Canadian Mortgage Calculator', description: 'Calculate Canadian mortgage payments and amortization.', category: 'financial', emoji: '🍁', keywords: ['canadian mortgage', 'canada mortgage', 'cmhc'] },
  { slug: 'mortgage-amortization-calculator', name: 'Mortgage Amortization Calculator', description: 'Generate detailed mortgage amortization schedules.', category: 'financial', emoji: '📋', keywords: ['mortgage amortization', 'amortization schedule', 'payoff schedule'] },
  { slug: 'percent-off-calculator', name: 'Percent Off Calculator', description: 'Calculate the final price after a percentage discount.', category: 'financial', emoji: '🏷️', keywords: ['percent off', 'discount', 'sale price'] },

  // HEALTH & FITNESS CALCULATORS
  { slug: 'bmi-calculator', name: 'BMI Calculator', description: 'Calculate Body Mass Index and healthy weight ranges.', category: 'health', emoji: '⚖️', keywords: ['bmi', 'body mass index', 'weight', 'height'], featured: true },
  { slug: 'calorie-calculator', name: 'Calorie Calculator', description: 'Calculate daily calorie needs based on activity level.', category: 'health', emoji: '🥗', keywords: ['calorie', 'calories', 'diet', 'nutrition'], featured: true },
  { slug: 'body-fat-calculator', name: 'Body Fat Calculator', description: 'Calculate body fat percentage using measurements.', category: 'health', emoji: '💪', keywords: ['body fat', 'body composition', 'fat percentage'] },
  { slug: 'bmr-calculator', name: 'BMR Calculator', description: 'Calculate Basal Metabolic Rate - calories burned at rest.', category: 'health', emoji: '🔥', keywords: ['bmr', 'basal metabolic rate', 'metabolism', 'calories'] },
  { slug: 'macro-calculator', name: 'Macro Calculator', description: 'Calculate daily macronutrient targets for your goals.', category: 'health', emoji: '🥩', keywords: ['macro', 'macronutrients', 'protein', 'carbs', 'fat'] },
  { slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', description: 'Calculate your ideal body weight range.', category: 'health', emoji: '🎯', keywords: ['ideal weight', 'healthy weight', 'target weight'] },
  { slug: 'pregnancy-calculator', name: 'Pregnancy Calculator', description: 'Track pregnancy progress and calculate important dates.', category: 'health', emoji: '🤰', keywords: ['pregnancy', 'due date', 'weeks pregnant', 'trimester'] },
  { slug: 'pregnancy-weight-gain-calculator', name: 'Pregnancy Weight Gain Calculator', description: 'Track recommended weight gain during pregnancy.', category: 'health', emoji: '🍼', keywords: ['pregnancy weight', 'gestational weight', 'prenatal'] },
  { slug: 'due-date-calculator', name: 'Due Date Calculator', description: 'Calculate pregnancy due date and gestational age.', category: 'health', emoji: '📅', keywords: ['due date', 'pregnancy', 'gestational age', 'edd'] },
  { slug: 'pace-calculator', name: 'Pace Calculator', description: 'Calculate running pace, distance, or time for any run.', category: 'health', emoji: '🏃', keywords: ['pace', 'running', 'marathon', 'race time'] },
  { slug: 'army-body-fat-calculator', name: 'Army Body Fat Calculator', description: 'Calculate body fat using the US Army measurement method.', category: 'health', emoji: '🎖️', keywords: ['army body fat', 'military', 'body fat tape test'] },
  { slug: 'carbohydrate-calculator', name: 'Carbohydrate Calculator', description: 'Calculate daily carbohydrate intake requirements.', category: 'health', emoji: '🍞', keywords: ['carbohydrate', 'carbs', 'glucose', 'nutrition'] },
  { slug: 'lean-body-mass-calculator', name: 'Lean Body Mass Calculator', description: 'Calculate lean body mass and muscle mass estimates.', category: 'health', emoji: '💪', keywords: ['lean body mass', 'muscle mass', 'lbm'] },
  { slug: 'healthy-weight-calculator', name: 'Healthy Weight Calculator', description: 'Determine your healthy weight range for your height.', category: 'health', emoji: '✅', keywords: ['healthy weight', 'normal weight', 'bmi range'] },
  { slug: 'calories-burned-calculator', name: 'Calories Burned Calculator', description: 'Estimate calories burned during various activities.', category: 'health', emoji: '🏋️', keywords: ['calories burned', 'exercise', 'activity', 'workout'] },
  { slug: 'one-rep-max-calculator', name: 'One Rep Max Calculator', description: 'Calculate your one rep max for weight training exercises.', category: 'health', emoji: '🏋️', keywords: ['one rep max', '1rm', 'strength', 'weightlifting'] },
  { slug: 'target-heart-rate-calculator', name: 'Target Heart Rate Calculator', description: 'Calculate target heart rate zones for optimal exercise.', category: 'health', emoji: '❤️', keywords: ['heart rate', 'target heart rate', 'exercise zone', 'cardio'] },
  { slug: 'protein-calculator', name: 'Protein Calculator', description: 'Calculate daily protein intake requirements.', category: 'health', emoji: '🥚', keywords: ['protein', 'protein intake', 'muscle building', 'nutrition'] },
  { slug: 'fat-intake-calculator', name: 'Fat Intake Calculator', description: 'Calculate healthy daily fat intake requirements.', category: 'health', emoji: '🥑', keywords: ['fat intake', 'dietary fat', 'nutrition', 'fat gram'] },
  { slug: 'tdee-calculator', name: 'TDEE Calculator', description: 'Calculate Total Daily Energy Expenditure for weight management.', category: 'health', emoji: '⚡', keywords: ['tdee', 'total daily energy', 'calories burned', 'maintenance calories'] },
  { slug: 'ovulation-calculator', name: 'Ovulation Calculator', description: 'Calculate ovulation dates and fertile window.', category: 'health', emoji: '🌸', keywords: ['ovulation', 'fertile window', 'conception', 'period'] },
  { slug: 'period-calculator', name: 'Period Calculator', description: 'Track menstrual cycle and predict future periods.', category: 'health', emoji: '📅', keywords: ['period', 'menstrual cycle', 'period tracker'] },
  { slug: 'gfr-calculator', name: 'GFR Calculator', description: 'Calculate Glomerular Filtration Rate for kidney health.', category: 'health', emoji: '🫘', keywords: ['gfr', 'kidney function', 'creatinine', 'renal'] },
  { slug: 'body-type-calculator', name: 'Body Type Calculator', description: 'Determine your body type (ectomorph, mesomorph, endomorph).', category: 'health', emoji: '🧍', keywords: ['body type', 'somatotype', 'ectomorph', 'mesomorph'] },
  { slug: 'body-surface-area-calculator', name: 'Body Surface Area Calculator', description: 'Calculate body surface area for medical purposes.', category: 'health', emoji: '📐', keywords: ['body surface area', 'bsa', 'medical', 'dosage'] },
  { slug: 'bac-calculator', name: 'BAC Calculator', description: 'Estimate Blood Alcohol Content based on drinks consumed.', category: 'health', emoji: '🍺', keywords: ['bac', 'blood alcohol', 'alcohol', 'drinking'] },
  { slug: 'weight-watchers-points-calculator', name: 'Weight Watcher Points Calculator', description: 'Calculate Weight Watchers points for foods and activities.', category: 'health', emoji: '⭐', keywords: ['weight watchers', 'ww points', 'smartpoints', 'diet'] },
  { slug: 'overweight-calculator', name: 'Overweight Calculator', description: 'Determine if you are overweight using BMI and other metrics.', category: 'health', emoji: '📊', keywords: ['overweight', 'obese', 'bmi', 'weight category'] },

  // MATH CALCULATORS
  { slug: 'scientific-calculator', name: 'Scientific Calculator', description: 'Full-featured scientific calculator with advanced functions.', category: 'math', emoji: '🧮', keywords: ['scientific calculator', 'sin', 'cos', 'tan', 'logarithm'], featured: true },
  { slug: 'fraction-calculator', name: 'Fraction Calculator', description: 'Add, subtract, multiply, and divide fractions.', category: 'math', emoji: '½', keywords: ['fraction', 'numerator', 'denominator', 'simplify'] },
  { slug: 'percentage-calculator', name: 'Percentage Calculator', description: 'Calculate percentages, percent increase, and percent decrease.', category: 'math', emoji: '%', keywords: ['percentage', 'percent', 'percent change', 'percent of'] },
  { slug: 'triangle-calculator', name: 'Triangle Calculator', description: 'Calculate triangle sides, angles, area, and perimeter.', category: 'math', emoji: '📐', keywords: ['triangle', 'hypotenuse', 'angle', 'area', 'perimeter'] },
  { slug: 'volume-calculator', name: 'Volume Calculator', description: 'Calculate volume of 3D shapes including cubes, spheres, cylinders.', category: 'math', emoji: '📦', keywords: ['volume', 'cube', 'sphere', 'cylinder', '3d shape'] },
  { slug: 'standard-deviation-calculator', name: 'Standard Deviation Calculator', description: 'Calculate standard deviation, variance, and statistics.', category: 'math', emoji: 'σ', keywords: ['standard deviation', 'variance', 'statistics', 'mean'] },
  { slug: 'random-number-generator', name: 'Random Number Generator', description: 'Generate random numbers within any specified range.', category: 'math', emoji: '🎲', keywords: ['random number', 'random', 'generator', 'dice'] },
  { slug: 'number-sequence-calculator', name: 'Number Sequence Calculator', description: 'Find patterns and calculate terms in number sequences.', category: 'math', emoji: '🔢', keywords: ['number sequence', 'arithmetic sequence', 'geometric sequence', 'pattern'] },
  { slug: 'percent-error-calculator', name: 'Percent Error Calculator', description: 'Calculate percent error for measurements and experiments.', category: 'math', emoji: '🔬', keywords: ['percent error', 'error calculation', 'experimental error'] },
  { slug: 'exponent-calculator', name: 'Exponent Calculator', description: 'Calculate powers and exponents for any base and exponent.', category: 'math', emoji: 'xⁿ', keywords: ['exponent', 'power', 'base', 'squared', 'cubed'] },
  { slug: 'binary-calculator', name: 'Binary Calculator', description: 'Perform arithmetic operations with binary numbers.', category: 'math', emoji: '0️⃣', keywords: ['binary', 'binary calculator', 'base 2', 'bit'] },
  { slug: 'hex-calculator', name: 'Hex Calculator', description: 'Perform calculations with hexadecimal numbers.', category: 'math', emoji: '🔡', keywords: ['hex', 'hexadecimal', 'base 16', 'color code'] },
  { slug: 'half-life-calculator', name: 'Half-Life Calculator', description: 'Calculate radioactive decay and half-life problems.', category: 'math', emoji: '☢️', keywords: ['half life', 'radioactive decay', 'nuclear', 'decay constant'] },
  { slug: 'quadratic-formula-calculator', name: 'Quadratic Formula Calculator', description: 'Solve quadratic equations using the quadratic formula.', category: 'math', emoji: '📉', keywords: ['quadratic', 'quadratic formula', 'equation', 'roots'] },
  { slug: 'slope-calculator', name: 'Slope Calculator', description: 'Calculate the slope of a line from two points.', category: 'math', emoji: '↗️', keywords: ['slope', 'gradient', 'rise over run', 'linear'] },
  { slug: 'log-calculator', name: 'Log Calculator', description: 'Calculate logarithms and natural logarithms.', category: 'math', emoji: 'ln', keywords: ['logarithm', 'log', 'natural log', 'ln'] },
  { slug: 'area-calculator', name: 'Area Calculator', description: 'Calculate area of squares, rectangles, triangles, circles.', category: 'math', emoji: '⬜', keywords: ['area', 'square', 'rectangle', 'circle', 'shape area'] },
  { slug: 'sample-size-calculator', name: 'Sample Size Calculator', description: 'Calculate the required sample size for surveys and studies.', category: 'math', emoji: '📊', keywords: ['sample size', 'survey', 'confidence level', 'margin of error'] },
  { slug: 'probability-calculator', name: 'Probability Calculator', description: 'Calculate probability of events and combinations.', category: 'math', emoji: '🎯', keywords: ['probability', 'chance', 'odds', 'statistics'] },
  { slug: 'statistics-calculator', name: 'Statistics Calculator', description: 'Calculate mean, median, mode, range, and more statistics.', category: 'math', emoji: '📈', keywords: ['statistics', 'mean', 'median', 'mode', 'range'] },
  { slug: 'mean-median-mode-calculator', name: 'Mean/Median/Mode Calculator', description: 'Calculate mean, median, mode, and range for data sets.', category: 'math', emoji: '📊', keywords: ['mean', 'median', 'mode', 'range', 'average', 'statistics'] },
  { slug: 'permutation-combination-calculator', name: 'Permutation and Combination Calculator', description: 'Calculate permutations and combinations (nPr and nCr).', category: 'math', emoji: '🔀', keywords: ['permutation', 'combination', 'npr', 'ncr', 'probability'] },
  { slug: 'z-score-calculator', name: 'Z-score Calculator', description: 'Calculate z-scores and standard normal distribution.', category: 'math', emoji: 'z', keywords: ['z score', 'standard normal', 'z-test', 'normal distribution'] },
  { slug: 'confidence-interval-calculator', name: 'Confidence Interval Calculator', description: 'Calculate confidence intervals for statistical analysis.', category: 'math', emoji: '📏', keywords: ['confidence interval', 'statistics', 'ci', 'margin of error'] },
  { slug: 'ratio-calculator', name: 'Ratio Calculator', description: 'Simplify ratios and calculate equivalent ratios.', category: 'math', emoji: '⚖️', keywords: ['ratio', 'proportion', 'equivalent ratio', 'simplify'] },
  { slug: 'distance-calculator', name: 'Distance Calculator', description: 'Calculate distance between two points.', category: 'math', emoji: '📍', keywords: ['distance', 'coordinates', 'distance formula', 'length'] },
  { slug: 'circle-calculator', name: 'Circle Calculator', description: 'Calculate circle area, circumference, diameter, and radius.', category: 'math', emoji: '⭕', keywords: ['circle', 'radius', 'diameter', 'circumference', 'area'] },
  { slug: 'surface-area-calculator', name: 'Surface Area Calculator', description: 'Calculate surface area of 3D shapes.', category: 'math', emoji: '📐', keywords: ['surface area', '3d shape', 'cube', 'sphere', 'cylinder'] },
  { slug: 'pythagorean-theorem-calculator', name: 'Pythagorean Theorem Calculator', description: 'Calculate sides of right triangles using the Pythagorean theorem.', category: 'math', emoji: '📐', keywords: ['pythagorean', 'right triangle', 'hypotenuse', 'pythagoras'] },
  { slug: 'right-triangle-calculator', name: 'Right Triangle Calculator', description: 'Solve right triangles given sides or angles.', category: 'math', emoji: '📐', keywords: ['right triangle', 'hypotenuse', 'legs', 'angles'] },
  { slug: 'root-calculator', name: 'Root Calculator', description: 'Calculate square roots, cube roots, and nth roots.', category: 'math', emoji: '√', keywords: ['root', 'square root', 'cube root', 'nth root'] },
  { slug: 'lcm-calculator', name: 'Least Common Multiple Calculator', description: 'Find the Least Common Multiple (LCM) of numbers.', category: 'math', emoji: '🔢', keywords: ['lcm', 'least common multiple', 'multiples', 'fractions'] },
  { slug: 'gcf-calculator', name: 'Greatest Common Factor Calculator', description: 'Find the Greatest Common Factor (GCF) of numbers.', category: 'math', emoji: '🔢', keywords: ['gcf', 'gcd', 'greatest common factor', 'divisor'] },
  { slug: 'factor-calculator', name: 'Factor Calculator', description: 'Find all factors of a number.', category: 'math', emoji: '÷', keywords: ['factor', 'factors', 'divisors', 'factoring'] },
  { slug: 'rounding-calculator', name: 'Rounding Calculator', description: 'Round numbers to any decimal place or significant figure.', category: 'math', emoji: '🔄', keywords: ['rounding', 'round number', 'decimal places', 'significant figures'] },
  { slug: 'matrix-calculator', name: 'Matrix Calculator', description: 'Perform matrix operations: addition, multiplication, determinant.', category: 'math', emoji: '🔲', keywords: ['matrix', 'matrices', 'determinant', 'linear algebra'] },
  { slug: 'scientific-notation-calculator', name: 'Scientific Notation Calculator', description: 'Convert numbers to and from scientific notation.', category: 'math', emoji: '🔬', keywords: ['scientific notation', 'exponent', 'power of 10', 'scientific format'] },
  { slug: 'big-number-calculator', name: 'Big Number Calculator', description: 'Perform arithmetic with very large numbers.', category: 'math', emoji: '∞', keywords: ['big number', 'large number', 'arbitrary precision', 'overflow'] },
  { slug: 'prime-factorization-calculator', name: 'Prime Factorization Calculator', description: 'Find the prime factorization of any number.', category: 'math', emoji: '🔢', keywords: ['prime factorization', 'prime factors', 'prime numbers'] },
  { slug: 'average-calculator', name: 'Average Calculator', description: 'Calculate the average (mean) of a list of numbers.', category: 'math', emoji: '📊', keywords: ['average', 'mean', 'arithmetic mean', 'numbers'] },

  // UTILITY & OTHER CALCULATORS
  { slug: 'age-calculator', name: 'Age Calculator', description: 'Calculate exact age in years, months, and days.', category: 'utility', emoji: '🎂', keywords: ['age', 'birthday', 'date of birth', 'how old'], featured: true },
  { slug: 'date-calculator', name: 'Date Calculator', description: 'Calculate the difference between dates and add/subtract days.', category: 'utility', emoji: '📅', keywords: ['date', 'date difference', 'days between', 'calendar'] },
  { slug: 'time-calculator', name: 'Time Calculator', description: 'Add and subtract time values, convert time units.', category: 'utility', emoji: '⏰', keywords: ['time', 'hours', 'minutes', 'seconds', 'duration'] },
  { slug: 'hours-calculator', name: 'Hours Calculator', description: 'Calculate total hours worked and elapsed time.', category: 'utility', emoji: '🕐', keywords: ['hours', 'work hours', 'time tracking', 'payroll'] },
  { slug: 'gpa-calculator', name: 'GPA Calculator', description: 'Calculate Grade Point Average for academic performance.', category: 'utility', emoji: '🎓', keywords: ['gpa', 'grade point average', 'grades', 'academic'] },
  { slug: 'grade-calculator', name: 'Grade Calculator', description: 'Calculate final grades and weighted averages.', category: 'utility', emoji: '📝', keywords: ['grade', 'grades', 'final grade', 'weighted average'] },
  { slug: 'height-calculator', name: 'Height Calculator', description: 'Convert height between feet/inches and centimeters.', category: 'utility', emoji: '📏', keywords: ['height', 'tall', 'feet to cm', 'cm to feet', 'inches'] },
  { slug: 'concrete-calculator', name: 'Concrete Calculator', description: 'Calculate how much concrete you need for projects.', category: 'utility', emoji: '🏗️', keywords: ['concrete', 'cement', 'cubic yards', 'construction'] },
  { slug: 'ip-subnet-calculator', name: 'IP Subnet Calculator', description: 'Calculate IP addresses, subnet masks, and network ranges.', category: 'utility', emoji: '🌐', keywords: ['ip subnet', 'network', 'cidr', 'ip address', 'subnet mask'] },
  { slug: 'bra-size-calculator', name: 'Bra Size Calculator', description: 'Calculate bra size from bust and underbust measurements.', category: 'utility', emoji: '👙', keywords: ['bra size', 'cup size', 'measurements', 'lingerie'] },
  { slug: 'password-generator', name: 'Password Generator', description: 'Generate strong, secure passwords for any use.', category: 'utility', emoji: '🔐', keywords: ['password', 'password generator', 'secure', 'random password'] },
  { slug: 'dice-roller', name: 'Dice Roller', description: 'Roll dice of any size for games and random numbers.', category: 'utility', emoji: '🎲', keywords: ['dice', 'dice roller', 'd20', 'd6', 'random', 'rpg'] },
  { slug: 'conversion-calculator', name: 'Conversion Calculator', description: 'Convert between various units of measurement.', category: 'utility', emoji: '🔄', keywords: ['conversion', 'convert', 'unit conversion', 'measurement'] },
  { slug: 'fuel-cost-calculator', name: 'Fuel Cost Calculator', description: 'Calculate fuel cost for road trips and commutes.', category: 'utility', emoji: '⛽', keywords: ['fuel cost', 'gas cost', 'road trip', 'mpg'] },
  { slug: 'voltage-drop-calculator', name: 'Voltage Drop Calculator', description: 'Calculate voltage drop in electrical wiring.', category: 'utility', emoji: '⚡', keywords: ['voltage drop', 'electrical', 'wire gauge', 'current'] },
  { slug: 'btu-calculator', name: 'BTU Calculator', description: 'Calculate BTU requirements for heating and cooling.', category: 'utility', emoji: '🌡️', keywords: ['btu', 'heating', 'cooling', 'air conditioner', 'hvac'] },
  { slug: 'square-footage-calculator', name: 'Square Footage Calculator', description: 'Calculate the square footage of rooms and spaces.', category: 'utility', emoji: '📐', keywords: ['square footage', 'area', 'room size', 'floor area'] },
  { slug: 'time-card-calculator', name: 'Time Card Calculator', description: 'Calculate total work hours from time card entries.', category: 'utility', emoji: '🗂️', keywords: ['time card', 'work hours', 'payroll', 'timesheet'] },
  { slug: 'time-zone-calculator', name: 'Time Zone Calculator', description: 'Convert times between different time zones worldwide.', category: 'utility', emoji: '🌍', keywords: ['time zone', 'utc', 'gmt', 'world time', 'convert time'] },
  { slug: 'love-calculator', name: 'Love Calculator', description: 'Calculate love compatibility between two names.', category: 'utility', emoji: '❤️', keywords: ['love', 'compatibility', 'relationship', 'romance'] },
  { slug: 'gdp-calculator', name: 'GDP Calculator', description: 'Calculate Gross Domestic Product using expenditure approach.', category: 'utility', emoji: '📊', keywords: ['gdp', 'gross domestic product', 'economy', 'economic growth'] },
  { slug: 'gas-mileage-calculator', name: 'Gas Mileage Calculator', description: 'Calculate gas mileage (MPG) and fuel efficiency.', category: 'utility', emoji: '🚘', keywords: ['gas mileage', 'mpg', 'fuel efficiency', 'fuel economy'] },
  { slug: 'horsepower-calculator', name: 'Horsepower Calculator', description: 'Calculate horsepower from torque and RPM.', category: 'utility', emoji: '🐎', keywords: ['horsepower', 'hp', 'torque', 'rpm', 'engine power'] },
  { slug: 'engine-horsepower-calculator', name: 'Engine Horsepower Calculator', description: 'Estimate engine horsepower using ET or trap speed.', category: 'utility', emoji: '🏎️', keywords: ['engine horsepower', 'dyno', 'quarter mile', 'engine'] },
  { slug: 'stair-calculator', name: 'Stair Calculator', description: 'Calculate stair dimensions for construction.', category: 'utility', emoji: '🪜', keywords: ['stair', 'stairs', 'riser', 'tread', 'construction'] },
  { slug: 'resistor-calculator', name: 'Resistor Calculator', description: 'Calculate resistor values from color bands or E-series.', category: 'utility', emoji: '⚡', keywords: ['resistor', 'ohm', 'color band', 'electronics'] },
  { slug: 'ohms-law-calculator', name: "Ohm's Law Calculator", description: "Apply Ohm's Law to calculate voltage, current, and resistance.", category: 'utility', emoji: '🔌', keywords: ["ohm's law", 'voltage', 'current', 'resistance', 'electronics'] },
  { slug: 'electricity-calculator', name: 'Electricity Calculator', description: 'Calculate electricity costs and power consumption.', category: 'utility', emoji: '💡', keywords: ['electricity', 'kwh', 'power consumption', 'electric bill'] },
  { slug: 'shoe-size-calculator', name: 'Shoe Size Conversion', description: 'Convert shoe sizes between US, UK, EU, and other systems.', category: 'utility', emoji: '👟', keywords: ['shoe size', 'footwear', 'us uk eu', 'foot measurement'] },
  { slug: 'tip-calculator', name: 'Tip Calculator', description: 'Calculate tip amount and split bills at restaurants.', category: 'utility', emoji: '🍽️', keywords: ['tip', 'gratuity', 'split bill', 'restaurant', 'service charge'], featured: true },
  { slug: 'mileage-calculator', name: 'Mileage Calculator', description: 'Calculate mileage, distance, and travel costs.', category: 'utility', emoji: '🗺️', keywords: ['mileage', 'distance', 'travel cost', 'odometer'] },
  { slug: 'density-calculator', name: 'Density Calculator', description: 'Calculate density, mass, or volume from two known values.', category: 'utility', emoji: '🧪', keywords: ['density', 'mass', 'volume', 'physics'] },
  { slug: 'mass-calculator', name: 'Mass Calculator', description: 'Calculate mass from density and volume.', category: 'utility', emoji: '⚖️', keywords: ['mass', 'weight', 'density', 'volume'] },
  { slug: 'weight-calculator', name: 'Weight Calculator', description: 'Convert weight between different units.', category: 'utility', emoji: '⚖️', keywords: ['weight', 'kg to lbs', 'pounds', 'kilograms', 'conversion'] },
  { slug: 'speed-calculator', name: 'Speed Calculator', description: 'Calculate speed, distance, or time for any motion.', category: 'utility', emoji: '🏎️', keywords: ['speed', 'velocity', 'mph', 'kmh', 'distance', 'time'] },
  { slug: 'molarity-calculator', name: 'Molarity Calculator', description: 'Calculate molarity and solution concentrations.', category: 'utility', emoji: '⚗️', keywords: ['molarity', 'moles', 'concentration', 'chemistry', 'solution'] },
  { slug: 'molecular-weight-calculator', name: 'Molecular Weight Calculator', description: 'Calculate the molecular weight of chemical compounds.', category: 'utility', emoji: '🧬', keywords: ['molecular weight', 'molar mass', 'chemistry', 'formula'] },
  { slug: 'roman-numeral-converter', name: 'Roman Numeral Converter', description: 'Convert between Arabic and Roman numerals.', category: 'utility', emoji: 'Ⅻ', keywords: ['roman numeral', 'roman', 'iv', 'xi', 'convert number'] },
  { slug: 'golf-handicap-calculator', name: 'Golf Handicap Calculator', description: 'Calculate your golf handicap index.', category: 'utility', emoji: '⛳', keywords: ['golf', 'handicap', 'golf handicap', 'golf score'] },
  { slug: 'sleep-calculator', name: 'Sleep Calculator', description: 'Calculate optimal sleep and wake times for REM cycles.', category: 'utility', emoji: '😴', keywords: ['sleep', 'sleep cycles', 'wake time', 'rem sleep'] },
  { slug: 'tire-size-calculator', name: 'Tire Size Calculator', description: 'Compare tire sizes and calculate tire dimensions.', category: 'utility', emoji: '🔄', keywords: ['tire size', 'wheel size', 'aspect ratio', 'tire comparison'] },
  { slug: 'roofing-calculator', name: 'Roofing Calculator', description: 'Calculate roofing materials and square footage.', category: 'utility', emoji: '🏠', keywords: ['roofing', 'roof', 'shingles', 'squares', 'construction'] },
  { slug: 'tile-calculator', name: 'Tile Calculator', description: 'Calculate the number of tiles needed for any room.', category: 'utility', emoji: '🟫', keywords: ['tile', 'tiles', 'flooring', 'bathroom', 'kitchen'] },
  { slug: 'mulch-calculator', name: 'Mulch Calculator', description: 'Calculate how much mulch you need for your garden.', category: 'utility', emoji: '🌱', keywords: ['mulch', 'garden', 'landscaping', 'cubic yards'] },
  { slug: 'gravel-calculator', name: 'Gravel Calculator', description: 'Calculate how much gravel you need for driveways and paths.', category: 'utility', emoji: '🪨', keywords: ['gravel', 'driveway', 'landscaping', 'tons', 'cubic yards'] },
  { slug: 'wind-chill-calculator', name: 'Wind Chill Calculator', description: 'Calculate wind chill temperature and feel-like temperatures.', category: 'utility', emoji: '🌬️', keywords: ['wind chill', 'feels like', 'winter', 'temperature', 'weather'] },
  { slug: 'heat-index-calculator', name: 'Heat Index Calculator', description: 'Calculate heat index (apparent temperature) with humidity.', category: 'utility', emoji: '🌡️', keywords: ['heat index', 'feels like', 'humidity', 'apparent temperature'] },
  { slug: 'dew-point-calculator', name: 'Dew Point Calculator', description: 'Calculate dew point temperature from relative humidity.', category: 'utility', emoji: '💧', keywords: ['dew point', 'humidity', 'weather', 'condensation'] },
  { slug: 'bandwidth-calculator', name: 'Bandwidth Calculator', description: 'Calculate download time and data transfer speeds.', category: 'utility', emoji: '📡', keywords: ['bandwidth', 'download speed', 'internet speed', 'data transfer'] },
  { slug: 'base64-calculator', name: 'Base64 Encode/Decode', description: 'Encode and decode text to/from Base64 format.', category: 'utility', emoji: '💻', keywords: ['base64', 'encode', 'decode', 'encoding'] },
  { slug: 'url-encoder', name: 'URL Encode/Decode', description: 'Encode and decode URLs and special characters.', category: 'utility', emoji: '🔗', keywords: ['url encode', 'url decode', 'percent encoding', 'uri'] },
  { slug: 'time-duration-calculator', name: 'Time Duration Calculator', description: 'Calculate the duration between two times.', category: 'utility', emoji: '⏱️', keywords: ['time duration', 'elapsed time', 'time between', 'hours minutes'] },
  { slug: 'day-counter', name: 'Day Counter', description: 'Count the number of days between two dates.', category: 'utility', emoji: '📆', keywords: ['day counter', 'days between', 'date difference', 'countdown'] },
  { slug: 'day-of-week-calculator', name: 'Day of the Week Calculator', description: 'Find what day of the week any date falls on.', category: 'utility', emoji: '📅', keywords: ['day of week', 'what day', 'calendar', 'date'] },
  { slug: 'construction-calculator', name: 'Construction Calculator', description: 'Various construction measurements and material calculations.', category: 'utility', emoji: '🏗️', keywords: ['construction', 'building', 'materials', 'measurements'] },
  { slug: 'paint-calculator', name: 'Paint Calculator', description: 'Calculate how much paint you need for any room.', category: 'utility', emoji: '🎨', keywords: ['paint', 'gallons', 'painting', 'wall coverage', 'room'] },
];

export function getCalculatorBySlug(slug: string): Calculator | undefined {
  return calculators.find(c => c.slug === slug);
}

export function getCalculatorsByCategory(category: string): Calculator[] {
  return calculators.filter(c => c.category === category);
}

export function getFeaturedCalculators(): Calculator[] {
  return calculators.filter(c => c.featured);
}

export function searchCalculators(query: string): Calculator[] {
  const q = query.toLowerCase();
  return calculators.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.description.toLowerCase().includes(q) ||
    c.keywords.some(k => k.toLowerCase().includes(q))
  );
}
